ministryofjustice/bichard7-next-core

src/use-cases/PopulateOffenceResults.ts, src/use-cases/lookupPsaCodeByCrownCourtName.ts
Simplified the BA result qualifier logic in PopulateOffencesResult.
If BA qualifier is added to any of the HO results (`result.ResultQualifierVariable`), then depending on the value of `baResultCodeQualifierHasBeenExcluded` we might need to add BA qualifier to the list of Bail Qualifiers returned by the use case.
Also in this PR, renamed `organisationUnitLookup` use case to `lookupPsaCodeByCrownCourtName`.
=> Refactor BA qualifier logic in PopulateOffenceResults

src/use-cases/PopulateOffenceResults.ts, src/use-cases/PopulateOffences.ts, src/use-cases/populateDefendant.ts
- Fixed a typo
- Made class variables private
- Removed redundant `map()` calling
=> Refactor populate defendant, offence and result use cases

.eslintrc.js, jest.config.js, package.json, scripts/jest.setup.ts, tests/exceptions/HO100240_246.test.ts, tests/exceptions/HO100245.test.ts, tests/jest.d.ts, tsconfig.json
Some exceptions are hidden by legacy bichard; with new bichard we have the ability to raise these exceptions during validation.
In such cases we don't/ can't test these exceptions in legacy bichard but do want to test for these exceptions in new bichard (conditional testing) using the new syntax:
`it.ifNewBichard()`
=> test: 💍 add `it.ifNewBichard` to conditionally run tests

src/index.ts, src/lib/generateLegacyAhoXml.ts, src/lib/parseAhoXml.test.ts, src/lib/parseAhoXml.ts, src/types/AhoParsedXml.ts, src/types/RawAho.ts, test-data/AnnotatedHO1.xml, tests/comparison.test.ts
Currently, the core handler can handle incoming messages(XML) that are in SPI format, but it needs to handle incoming messages in AHO format.
- Add`parseAhoXml` function that maps the XML data into an AnnotatedHearingOutcome 
- Change the core handler to use the correct parser function based on the message structure
- Update comparison tests
> The parser is not complete, and not all the fields are implemented, but it can parse a simple AHO XML. `parseAhoXml` will evolve as we are fixing the issues from the comparison tests.
=> Bicaws 2050 Parse AHO xml

src/lib/generateLegacyAhoXml.ts, src/types/RawAho.ts, src/use-cases/enrichHearingOutcome/enrichFunctions/enrichCourtCases/enrichOffencesFromMatcherOutcome.ts, test-data/generated-aho.xml, tests/comparison.test.ts
which was causing the OffenceReasonSequence to be missed in the XML output
=> Fix a bug in the PNC Offence matching

src/lib/__snapshots__/parseAhoXml.test.ts.snap, src/lib/addExceptionsToRawAho.test.ts, src/lib/addExceptionsToRawAho.ts, src/lib/generateLegacyAhoXml.ts, src/lib/parseAhoXml.ts, src/types/RawAho.ts, tests/helpers/getPncQueryTimeFromAho.ts
We need to be able to add an "Error" attribute into elements for the output AHO XML. This PR:
- Updates the types from string to an object with text and error fields
- Turns on the setting in the parser to always generate a "#text" attribute (this makes the parsing more consistent, otherwise it could be a string or an object)
- add utility functions for setting the #text attribute in the output of the XML
- adds a function that maps through the exceptions and adds them in to the output AHO object
=> Add errors into the AHO XML

src/enrichAho/enrichFunctions/__snapshots__/enrichCourt.test.ts.snap, src/lib/decimalPlaces.ts, src/parse/parseAhoXml/__snapshots__/parseAhoXml.test.ts.snap, src/parse/parseAhoXml/parseAhoXml.ts, src/parse/parseSpiResult.ts, src/parse/transformSpiToAho/PopulateOffenceResults.ts, src/parse/transformSpiToAho/PopulateOffences.ts, src/parse/transformSpiToAho/__snapshots__/PopulateOffences.test.ts.snap, src/parse/transformSpiToAho/__snapshots__/populateDefendant.test.ts.snap, src/parse/transformSpiToAho/populateDefendant.ts, src/parse/transformSpiToAho/populateHearing.ts, src/schemas/annotatedHearingOutcome.ts, src/schemas/spiResult.ts, src/serialise/ahoXml/generate.ts, src/types/Plea.ts, tests/helpers/generateMockPncQueryResult.ts
All of the examples had values like `85.00` which we were converting to a number and then outputting with two decimal places so it matched. However, in Bichard there are values like `85` which were output without the decimal places. This stores the decimal places in the input so we can use it again in the output. It shouldn't really affect behaviour, so when we go live we can switch back to always using two decimal places and simplify this again.
=> Store the decimal places for AmountSpecifiedInResult so we match Bichard

README.md, src/comparison/cli/cache.ts, src/comparison/cli/getArgs.ts, src/comparison/cli/main.ts, src/comparison/cli/processFile.ts, src/comparison/cli/processRange.ts
Some notes:
- It caches the files in the /tmp directory as this will get cleaned up automatically by the OS. This reduces the risk of files hanging around
- If you run the tool with caching disabled it will clear the cache
Joe had a good idea to spin up a Docker container to give you a temporary terminal to run the comparisons in so that there's even less chance of the cached files being persisted, however until we implement that, use this carefully and clean up after yourself
=> Implement caching in the CLI comparison tool

src/dataLookup/index.ts, src/dataLookup/lookupCrownCourtByNameAndFirstPsaCode.ts, src/parse/transformSpiToAho/getRemandDetailsFromResultText.ts
* Fix a double-escaping issue in one of the regexes used to pull out court from the Result Text
* Use the PSA code for the extracted court to lookup the first court with that PSA code in the OU Data - as this is what Bichard does... We should definitely change this in the future!
=> Fix `NextResultSourceOrganisation` again

.github/workflows/release.yml, .npmrc, README.md, package.json
This PR adds a **manually triggered** GitHub Actions workflow that will build and publish the npm package.
Specifically, when manually triggered on the main branch, it will:
1. Check to make sure the version number in `package.json` hasn't already been published. If it has, it will fail the workflow with a helpful message saying to bump the version number.
2. Publish the package to npm using the [shared bichard7 user](https://www.npmjs.com/~bichard7)
=> Add GitHub Action to publish npm package

src/comparison/lambda.integration.test.ts, src/comparison/logInDynamoDb.integration.test.ts, src/comparison/logInDynamoDb.ts
This PR update comparison lambda to store the standing data version used in Bichard Core. We need this to compare it with the standing data version in Bichard that was used to generate the Processing Validation Result.
=> Store standing data version in comparison result record

src/comparison/cli/getDateFromComparisonFilePath.ts, src/comparison/cli/getStandingDataVersionByDate.ts, src/comparison/cli/main.ts, src/comparison/cli/processRange.ts
Also tweak the time handling because timezones were getting in the way and using the path was a lot simpler
=> Use an accurate time for the cutoff between versions of the standing data

src/lib/requireStandingData.ts
* Plonk some try catches around where we require lots of different versions of the `bichard7-next-data` package so it tries to import it in formats that work for both `webpack` and `npm`
This is a quick hack. There's probably a way to alter the webpack config to work off the `npm` import format (without specifying `node_modules/` before the import), but that's an improvement we can always make later
=> Fix standing data import for both webpack and npm packaging usecases

src/comparison/cli/cache.ts, src/comparison/compareLambda.integration.test.ts, src/comparison/compareLambda.ts, src/enrichAho/enrichFunctions/enrichDefendant/enrichDefendant.test.ts, src/enrichAho/enrichFunctions/enrichDefendant/enrichDefendant.ts, src/parse/parseAhoXml/parseAhoXml.ts, src/serialise/ahoXml/generate.ts, src/types/AhoXml.ts
This PR fixes some of the issues in comparison lambda:
- There was an issue with running the comparison using the CLI when the cache folder did not exist and `-c` flag was not set
- Compare lambda failed to log in DynamoDB when `compareMessage` threw an exception. It is now changed to handle the error and log a failed comparison record in DynamoDB so we can rerun them later (We currently miss comparison tests if they fail because of an exception)
- There was an issue with parsing GivenName in `parseAhoXml.ts`. The logic was assuming that GivenName is a string. Some of the comparison tests were failing because GivenName was an array. It updated to support both array and non-array strings.
- Also, when generating AHO XML, the logic was joining given names by white-space which was incorrect. …
=> Fix comparison lambda issues

src/enrichAho/enrichFunctions/enrichDefendant/enrichDefendant.test.ts, src/enrichAho/enrichFunctions/enrichDefendant/enrichDefendant.ts, src/parse/parseAhoXml/__snapshots__/parseAhoXml.test.ts.snap, src/parse/parseAhoXml/parseAhoXml.ts, src/parse/transformSpiToAho/PopulateOffences.ts, src/parse/transformSpiToAho/populateHearing.ts, src/schemas/annotatedHearingOutcome.ts, src/serialise/ahoXml/generate.ts, src/types/AhoXml.ts
In this PR:
- `DefendantDetail` changed to be optional. It is set if the defendant is an individual.
- `populateHearing` function updated to set `OrganisationName` field
- `OrganisationName` added to AHO XML. It is set if the defendant is corporate.
=> Fix comparison issue with corporate defendants

src/parse/parseAhoXml/parseAhoXml.ts, src/schemas/annotatedHearingOutcome.ts, src/schemas/spiResult.ts, src/serialise/ahoXml/generate.ts, src/types/AhoXml.ts
This fixes some of the issues in core:
- `LocationOfOffence` made optional for the following tests:
- `/2022/08/03/12/10/ProcessingValidation-33232a8d-3db9-4ac1-b801-5a10f4f113b6.json`
- `/2022/08/03/12/51/ProcessingValidation-ffd1faf7-f7ea-4185-96d6-1b0bad0f314f.json `
=> Make LocationOfOffence optional

src/comparison/cli/printResult.ts, src/comparison/compareMessage.ts
Does what it says on the tin. Prevents the comparison CLI from crashing when a test throws an error, and allows us to actually count them and run the rest of the tests in the range.
=> Catch errors in comparison CLI and show them in test summary

package.json, scripts/compareResults.ts, scripts/skip-test.ts, src/comparison/Types/ComparisonLog.ts, src/comparison/compareMessage.ts, src/comparison/getFailedComparisonResults.integration.test.ts, src/comparison/repeatTestBichard.ts, src/enrichAho/enrichFunctions/__snapshots__/enrichCase.test.ts.snap, src/enrichAho/enrichFunctions/__snapshots__/enrichCourt.test.ts.snap, src/enrichAho/enrichFunctions/__snapshots__/enrichForceOwner.test.ts.snap, src/enrichAho/enrichFunctions/enrichDefendant/enrichDefendant.ts, src/exceptions/HO100323.ts, src/parse/parseAhoXml/parseAhoXml.ts, src/parse/transformSpiToAho/populateHearing.ts, src/parse/transformSpiToAho/transformSpiToAho.ts, src/schemas/ahoValidations.ts, src/schemas/annotatedHearingOutcome.ts, src/schemas/spiResult.ts, src/serialise/ahoXml/generate.ts, src/types/AhoXml.ts, tsconfig.json
This PR:
- Fixes all of the errors and failures on the 4th and 5th July (which are largely solved by XML parsing/generation tweaks)
- Adds a script to skip comparison tests from the command-line (`npm run compare:skip <file> <skippedBy> <skippedReason>`)
- This adds the `skipped`, `skippedBy`, `skippedReason` fields to the record in Dynamo, and so needs to be run with `aws-vault`
- Adds an npm script for `compare:repeat`, and makes it work with S3 paths as well as local paths
=> Get 4th July passing again

src/enrichAho/enrichFunctions/enrichOffences/parseAsn.test.ts, src/enrichAho/enrichFunctions/enrichOffences/parseAsn.ts, src/parse/transformSpiToAho/PopulateOffences.ts, src/parse/transformSpiToAho/populateDefendant.ts, src/schemas/annotatedHearingOutcome.ts
This PR includes some more fixes for comparison tests. Specifically:
- Improving the ASN parsing so that the "valid length" metric is determined on a per-part basis, rather than once for the whole ASN
- Parsing an empty Person Title field in the XML as undefined, rather than an empty string
- Making the `adjournmentSineDieConditionMet` get cached between offences in the loop over offences, rather than getting re-calculated for each offence
=> More comparison test fixes

src/triggers/filterExcludedTriggers.ts
- A trigger should be excluded if it's in the excluded list for the force _OR_ the excluded list for the court (not _AND_!)
- A court excludes a trigger if _any_ of the possible keys for the court exclude the trigger (not if _all_ of them do!)
=> Fix boolean logic in filterExcludedTriggers

src/comparison/cli/getArgs.ts, src/comparison/cli/main.ts, src/comparison/lib/runMissingComparisons.ts
Added a new argument to the comparison CLI to run the missing comparison tests.
It lists S3 objects and checks whether they are processed and exist in DynamoDB. If not, it will invoke the comparison lambda.
Examples:
To run missing comparison tests for September 2022:
```
aws-vault exec qsolution-production -- npm run compare -- -m 2022/09
```
To run missing comparison tests for 1st September 2022:
```
aws-vault exec qsolution-production -- npm run compare -- -m 2022/09/01
```
To run missing comparison tests for 1st September 2022 at 1pm:
```
aws-vault exec qsolution-production -- npm run compare -- -m 2022/09/01/13
```
=> Update comparison cli to run missing comparison tests

.circleci/config.yml, src/triggers/TRPR0016.ts, src/triggers/filterExcludedTriggers.ts
There was a subtle bug in the logic used when deciding whether to filter out a trigger for a particular force/court - this PR fixes it (and makes some more comparison tests green!)
=> Fix bug in logic that excludes triggers based on court rules

src/comparison/lambdas/compareBatch.ts, src/comparison/lambdas/compareSingle.ts, src/comparison/lambdas/rerunAll.ts, src/comparison/lib/DynamoGateway.ts, src/comparison/lib/recordResultInDynamo.integration.test.ts, src/comparison/lib/recordResultInDynamo.ts, src/comparison/lib/recordResultsInDynamo.ts
This PR attempts to reduce the number of DynamoDB queries being made by the `compareBatch` lambda:
- All reads for the batch are now done in a single batch get dynamo query, rather than one read for each test
- All new inserts generated by running the test batch are now inserted in a single batch insert dynamo query, rather than one insert for each test
It also renames `logInDynamoDb` to a slightly more appropriate `recordResultInDynamo`.
=> compareBatch improvements

src/parse/transformSpiToAho/PopulateOffences.ts
This brings the behaviour in line with old Bichard, and fixes 3 of the comparison test failures :tada:
=> Only calculate adj sine die condition if there's no conviction date

src/lib/encoding.ts, src/parse/parseAhoXml/parseAhoXml.ts, src/parse/parseAnnotatedPNCUpdateDatasetXml/parseAnnotatedPNCUpdateDatasetXml.ts, src/parse/parseSpiResult.ts, src/serialise/ahoXml/generate.ts, tests/helpers/generateMockPncQueryResultFromAho.ts
We want to ensure we escape quotes inside the tag body values, but _not_ inside the attribute values!
=> Use separate entities encoders for attribute vs tag values in XML

src/exceptions/addExceptionsToAho.ts, src/lib/isPncException.ts, src/serialise/ahoXml/addExceptionsToAhoXml.ts
There is a priority when generating the XML where it will show the exception on the ASN element if no other exception exists
=> PNC exceptions can have duplicate paths on the AHO XML

.circleci/config.yml, environment/activemq.xml, environment/docker-compose.yml, package.json, scripts/compareResults.ts, src/comparison/lib/compareMessage.ts, src/index.ts, src/lib/MqGateway/MqGateway.integration.test.ts, src/lib/MqGateway/MqGateway.ts, src/lib/MqGateway/TestMqGateway.ts, src/lib/MqGateway/deconstructServers.test.ts, src/lib/MqGateway/deconstructServers.ts, src/lib/MqGateway/index.ts, src/lib/MqGateway/parseConnectionOptions.test.ts, src/lib/MqGateway/parseConnectionOptions.ts, src/lib/createMqConfig.ts, src/schemas/annotatedHearingOutcome.ts, src/steps/phase1/index.ts, src/steps/phase1/processPhase1.integration.test.ts, src/steps/phase1/processPhase1.ts, src/steps/phase1/sendToPhase2.integration.test.ts, src/steps/phase1/sendToPhase2.ts, src/steps/phase1/storeAuditLogEvents.integration.test.ts, src/types/MqConfig.ts, src/types/Phase1Result.ts, tests/helpers/processMessage.ts
This uses the MQ Gateway from audit logging as we don't have it in a shared library
=> Add the logic to ignore or send to phase 2

.github/workflows/update-npm-deps.yml
This PR allows manual trigger of update-deps github action.
Re-aligned node version to .nvmrc version.
=> update-npm-deps refresh

conductor/setup.sh, conductor/src/worker.ts, environment/docker-compose.yml
This PR configures the conductor worker in core to be able to connect to a Conductor instance that is running behind basic auth (which is what we're currently doing in AWS).
The worker now takes `$CONDUCTOR_USERNAME` and `$CONDUCTOR_PASSWORD` environment variables, which if specified, will attempt to use those credentials to connect via basic auth.
The setup script has also been adjusted to take the same variables and use them in the `curl` commands that are used to send data to the conductor API.
=> Add support for connecting to Conductor behind basic auth

.github/workflows/update-npm-deps.yml
This PR is to notify when the update `npm dependacies` script fails. It alerts the `moj-cjse-bichard-alerts` channel
=> Added GitHub actions alerts for failures

package.json, src/comparison/workers/rerunDay.ts
We're seeing some sporadic weird errors where the core worker fails to fetch files from S3. We suspect this is because we're trying to fetch so many files from S3 at the exact same instant.
This PR uses [p-limit](https://github.com/sindresorhus/p-limit) to neatly and succinctly manage the number of promises that get executed in parallel when using the map/`Promise.all()` pattern.
It's set to maximum 20 concurrent executions by default, but this can be changed with the `$S3_CONCURRENCY` environment variable.
=> Limit number of concurrent `compareFile()` invocations

src/enrichAho/enrichFunctions/enrichWithPncQuery.ts, src/exceptions/pncExceptions.ts
This means that that HO100314 is only raised in `src/exceptions/pncExceptions`, rather than in multiple places.
=> Remove "fix" for HO100314 and set a default pnc error message instead

scripts/summariseRecord.ts, src/comparison/cli/checkPncMatching.ts, src/comparison/cli/getArgs.ts, src/comparison/cli/main.ts, src/comparison/cli/printPncMatchingResult.ts, src/comparison/cli/processRange.ts, src/comparison/lib/comparePncMatching.ts, src/comparison/types/MatchingComparisonOutput.ts, src/comparison/types/PncComparisonResultDetail.ts, src/enrichAho/enrichFunctions/enrichCourtCases/offenceMatcher/offencesMatch.test.ts, src/enrichAho/enrichFunctions/enrichCourtCases/offenceMatcher/offencesMatch.ts, src/enrichAho/enrichFunctions/enrichWithPncQuery.ts, src/enrichAho/enrichFunctions/matchOffencesToPnc/Hypotheses.md, src/enrichAho/enrichFunctions/matchOffencesToPnc/README.md, src/enrichAho/enrichFunctions/matchOffencesToPnc/index.ts, src/enrichAho/enrichFunctions/matchOffencesToPnc/matchOffencesToPnc.test.ts, src/enrichAho/enrichFunctions/matchOffencesToPnc/matchOffencesToPnc.ts, tests/helpers/summariseMatching.ts, tests/matching.comparison.test.ts
This is the first pass at a new and simplified algorithm for the offence matching. It takes the following approach:
- Try to perfectly match everything (sequence number, offence code, dates)
* In a single case
* Across multiple cases
- Try to perfectly match everything apart from sequence number (offence code, dates)
* In a single case
* Across multiple cases
- Try to perfectly match everything apart from sequence number, but with fuzzy dates
* In a single case
* Across multiple cases
There's still some room for simplification and further refactoring. Currently this differs from the existing Bichard implementation in a couple of main ways:
- If we can perfectly match everything, but there are some duplicate offences, Bichard raises an exception, but we don't
- We are stricter if a user …
=> Update offence matching algorithm

.eslintrc.js, conductor/tasks/rerun_day.json, conductor/workflows/rerun-all.json, src/comparison/lib/comparePhase1.ts, src/comparison/workers/generateDayTasks.ts, src/comparison/workers/rerunDay.ts, src/enrichAho/enrichFunctions/matchOffencesToPnc/matchOffencesToPnc.test.ts, src/enrichAho/enrichFunctions/matchOffencesToPnc/matchOffencesToPnc.ts, src/exceptions/HO100321.ts, src/exceptions/addExceptionsToAho.ts
Also enable the conductor worker for re-running comparison tests to use the new matching algorithm
=> Implement the pnc matching annotation

.circleci/config.yml, conductor/tasks/rerun_day.json, src/comparison/workers/generateDayTasks.ts, src/comparison/workers/rerunDay.ts
And also make sure we're actually using the new matcher in the core worker!
=> Turn back on docker layer caching for e2e tests

scripts/summariseRecord.ts, src/comparison/lib/isIntentionalMatchingDifference/ho100333AndCCRHasLeadingZero.ts, src/comparison/lib/isIntentionalMatchingDifference/index.ts, src/enrichAho/enrichFunctions/matchOffencesToPnc/OffenceMatcher.ts, src/enrichAho/enrichFunctions/matchOffencesToPnc/matchOffencesToPnc.test.ts
Some fixes found by going through the comparison tests for 4th-8th July 2022.
- Stop filtering out final match candidates in some scenarios, don't treat them differently
- Mark cases where Bichard raises a HO100333 and core matches properly as intentional differences
- Use conviction dates when matching manual sequence numbers and there's more than one candidate offence that a manual sequence number could match to
Also adds some test todos for future tests that we should write, and add manual court case references to the summarise output.
=> More fixes for 1st week of July comparisons

.github/workflows/publish-architecture.yml
As I'm developing on MacOS not ubuntu a difference could be interfering.
I can't figure out why it's happening running the same docker command, and same npm command. The only difference is the base OS.
=> Try to use MacOS

src/enrichAho/enrichFunctions/enrichWithPncQuery.ts, src/index.ts, src/lib/CoreAuditLogger.test.ts, src/lib/CoreAuditLogger.ts, src/lib/auditLog/getAuditLogEvent.ts, src/lib/auditLog/getExceptionsGeneratedLog.ts, src/lib/auditLog/getIncomingMessageLog.ts, src/lib/auditLog/getTriggersGeneratedLog.ts, src/types/AuditLogEvent.ts, src/types/AuditLogger.ts, src/types/EventCategory.ts, src/types/Phase1Result.ts, src/workers/phase1/processPhase1.ts, src/workers/phase1/sendToPhase2.ts, src/workers/phase1/storeAuditLogEvents.integration.test.ts
This change was [suggested in a previous PR in the UI repo](https://github.com/ministryofjustice/bichard7-next-ui/pull/318#discussion_r1247905306). The UI repo uses the core repo package.
- Define a const for all possible audit log event options(event type and code)
- Use a const for eventSource and eventCategory
Use these types/const in the UI repo
=> Refactor: Define const for audit log event options and use enum for event source

README.md
Just a quick amendment to the readme to build the audit log api and event handler in the audit-logging repo
=> Updated readme to include steps to build audit log api and event handler

environment/postgres/schema.sql
PR to add the `incident_date` column to `service_messages` table in Postgres schema file.
=> Add incident date column to service messages table in pg schema file

environment/db-migrate.sh, environment/db-seed.sh, environment/docker-compose.yml, package.json
This PR updates the docker compose command in the db migration and seed scripts to use the old format. (`docker-compose` instead of `docker compose`)
It also updates `db-migrate` and `db-seed` docker compose services to add healthcheck and keep them running. The reason is that `--wait` flag expects the services to be healthy and running, otherwise docker compose command returns exit code 1.
=> Use older version of docker compose command in db migration scripts

environment/db-migrate.sh, environment/db-seed.sh
We now have healthcheck for `db-migrate` and `db-seed` services. Also these services keep running in the background. This PR is to update the `db-migrate.sh` and `db-seed.sh` scripts to wait for the service healthcheck instead of waiting for the services to exit.
=> Update db migrate and seed scripts to wait for the service healthcheck

environment/db-migrate.sh, environment/db-seed.sh, environment/docker-compose.yml, environment/postgres/liquibase/update.sh
This PR updates the `db-migrate` and `db-seed` docker compose services so that they will exit upon completion of their database scripts if the `EXIT_AFTER_SCRIPT` environment variable is set to `true`.
Additionally, `db-migrate.sh` and `db-seed.sh` scripts updated to set this environment variable to `true`. This is particularly important for our AWS pipeline, which relies on these scripts to manage database migration and seeding. By default, these services continue running in the background, but our usage of `docker compose run` necessitates that they gracefully terminate after executing their respective scripts.
=> Update db services to either keep in running state or exit using an env var

packages/conductor/workflows/bichard_process.json
Handle manually resolved case by completing workflow.
By default cases will go to resubmission. To complete manually the `isManuallyResolved` property must be passed in.
=> Handle manually resolved case

environment/docker-compose-bichard.yml, environment/docker-compose.yml, environment/local-conductor-worker.env, packages/message-forwarder/src/createStompClient.ts, packages/message-forwarder/src/forward-message.ts, packages/message-forwarder/src/server.ts
In addition to `mq` always sending to mq and `conductor` always continuing processing in Conductor (even if it didn’t start there) we decided to add `auto` that will check if the processing was started in Conductor and if it was, it will continue the workflow there, if not, it will send to mq. This will mean that during go-live, we'll continue to process old messages resubmissions in legacy Bichard and new ones will be using Conductor. It will make the transition a lot easier.
Also, use a proper logging library and log the correlation ID too
=> Add an auto option for the message forwarder

.gitignore, scripts/build-package.sh
This PR:
- Updates `.gitignore` to correctly ignore top-level `core` and `common` directories
- Updates the `build-package.sh` script to fail as soon any line in the file fails
=> Core and common in gitignore

package-lock.json, packages/core/conductor-tasks/incomingMessageHandler/alertCommonPlatform.integration.test.ts, packages/core/conductor-tasks/incomingMessageHandler/alertCommonPlatform.ts, packages/core/conductor-tasks/incomingMessageHandler/convertSpiToAho.integration.test.ts, packages/core/conductor-tasks/incomingMessageHandler/convertSpiToAho.ts, packages/core/conductor-tasks/types/errorReportData.ts, packages/core/package.json, packages/core/phase1/comparison/lib/DynamoGateway.integration.test.ts, packages/core/phase1/parse/transformSpiToAho/extractIncomingMessageData.ts, packages/core/phase1/parse/transformSpiToAho/transformIncomingMessageToAho.ts, packages/core/phase1/schemas/incomingMessage.ts
- Add error messages to conductor logs
- Add retry config for dynamo integration tests (hopefully will prevent CI flakes caused by an error we get when trying to set up tables in localstack instance)
- Set `SourceId` (external system identifier) as optional in incoming message schema
- Implements https://github.com/causaly/zod-validation-error for human readable outputs to parsing failures which can be sent out to CP
=> Fix incoming message parsing error

.circleci/config.yml
'install_api' and 'clone_bichard_repo' were not used. And 'working_directory: ~' gave errors.
=> Removed warnings and errors

packages/core/phase1/parse/parseAhoXml/parseAhoXml.ts, packages/core/phase1/parse/transformSpiToAho/PopulateOffenceResults.ts, packages/core/phase1/parse/transformSpiToAho/PopulateOffences.test.ts, packages/core/phase1/parse/transformSpiToAho/PopulateOffences.ts, packages/core/phase1/parse/transformSpiToAho/populateDefendant.ts, packages/core/phase1/parse/transformSpiToAho/populateHearing.ts, packages/core/phase1/parse/transformSpiToAho/transformIncomingMessageToAho.ts, packages/core/phase1/parse/transformSpiToAho/transformResultedCaseMessageToAho.ts, packages/core/phase1/parse/transformSpiToAho/transformSpiToAho.ts, packages/core/phase1/schemas/annotatedHearingOutcome.ts, packages/core/phase1/schemas/spiResult.ts, packages/core/phase1/serialise/ahoXml/generate.ts, packages/core/phase1/types/AhoXml.ts, packages/core/phase1/types/SpiResult.ts
In a couple of places in the code which converts from the incoming API message to our internal Annotated Hearing Outcome data structure, there were places where we used type casts before building up the object. This means that we can't guarantee that we're actually outputting a valid `AnnotatedHearingOutcome` data type (and more to the point, the typescript compiler won't tell us if this is the case). Now we're passing data between different stages in the workflow we'd like to be able to parse that data using Zod to make sure it's valid and we've got known inputs.
In a couple of places we weren't outputting all of the fields which means the data failed Zod parsing and raised an error.
This PR re-works the places we were using casting to use full types and makes sure that we know the data …
=> Tighten up the incoming message to aho conversion types

packages/core/comparison/lib/comparePhase2.ts
- Extract exceptions only once during parsing.
Calling the extract exceptions method on the xml introduced an inconsistency in the way we parsed xml exceptions into Exception[]
Fixes the comparison exception failures
=> Fix inconsistent phase2 exception parsing during comparison

packages/core/comparison/lib/comparePhase2.ts, packages/core/phase1/serialise/ahoXml/addAhoErrors.ts, packages/core/phase1/serialise/ahoXml/addExceptionsToAhoXml.ts, packages/core/phase1/serialise/ahoXml/serialiseToXml.ts, packages/core/phase2/lib/getDisFromResult/validateAmountSpecifiedInResult.test.ts, packages/core/phase2/serialise/pnc-update-dataset-xml/serialiseToXml.ts, packages/core/phase2/tests/fixtures/PncUpdateDataSet-with-result-class-error.xml
Incoming PncUpdateDataset result in a PncUpdateDataset message that does not have false hasError attributes.  This change introduces a parameter to control false hasError attributes which is true by default but passed in as false in the case of incoming PncUpdateDataset processing.
=> Phase 2: Fix hasError attributes for incoming PncUpdateDataset

README.md, package.json, scripts/open-conductor.sh
To access Conductor in a deployed environment, you have to retrieve the URL and password for it which is effort when you're working with Conductor and having to do a switcharoo between different environments all the time.
Add a lil script that retrieves the Conductor URL and password from AWS for the environment, and then saves the password to the clipboard and opens Conductor in the browser.
This can be run by doing:
```bash
aws-vault exec bichard7-shared-e2e-test -- npm run conductor:open
```
=> Add script to open Conductor for a deployed environment in the browser

packages/core/comparison/lib/comparePhase2.ts
This fixes a bunch of Phase 2 comparison tests related to the `WeedFlag`, similar to issues found in Phase 1.
=> Update Phase 2 comparison tests to normalise outgoing message

packages/core/comparison/conductor-tasks/generateRerunTasks.ts
Tasks are dynamically generated for the comparison tests in Conductor, each covering a portion of the date range set when starting the workflow. Currently, the names of these look like this:
- Update the task reference name to include the date range it's covering. We remove the milliseconds, but keep the seconds as a second is the smallest duration.
- Update task number to start from 1 (since we hoomans).
- Fix the log at the end of generating the rerun tasks as it assumes that the tasks will always be a day interval. It could be hours depending on the `durationSeconds` and the date range set.
=> Add date range to generated Conductor task names for comparison tests

packages/conductor/workflows/rerun-all.json, packages/conductor/workflows/rerun-failures.json, packages/core/comparison/conductor-tasks/generateRerunTasks.ts
3,600 seconds (1 hour) ends up generating a lot of tasks, so 43,200 seconds (12 hours) is a better balance.
Records began from 2023-02-08 for phase 2 comparisons, which we'll be using more now that Phase 1 is complete.
https://dsdmoj.atlassian.net/browse/BICAWS7-2836
=> Update input defaults for rerun Conductor workflows

packages/common/AuditLogApiClient/ApplicationError.ts, packages/common/AuditLogApiClient/AuditLogApiClient.ts, packages/conductor/e2e-test/incomingMessageHandler.e2e.test.ts, packages/conductor/tasks/create_audit_log_record.json, packages/conductor/workflows/incoming-message-handler.json, packages/core/conductor-tasks/incomingMessageHandler/createAuditLogRecord.integration.test.ts, packages/core/conductor-tasks/incomingMessageHandler/createAuditLogRecord.ts
Currently, if there is already an audit log record for this correlation ID, the workflow fails. This PR handles this more gracefully:
- if the correlation ID exists then it is a duplicate so we now go down the same code path as exists for this scenario
- if there is any other failure, then we still fail as before
Other considerations:
I have observed a failure mode where the `create_audit_log_record` task was started (and did create the record) but then timed out for reasons unknown. In this case we want to avoid then retrying and marking it as a duplicate so I've changed the task so that it doesn't retry and will cause the workflow to fail so that we can investigate.
=> Handle duplicate incoming message handler workflows gracefully

packages/common/conductor/middleware/s3TaskDataFetcher.ts, packages/common/s3/putFileToS3.ts, packages/common/s3/readS3FileTags.ts, packages/common/s3/writeS3FileTags.ts, packages/core/conductor-tasks/bichard_phase_1/persistPhase1.integration.test.ts, packages/core/conductor-tasks/bichard_phase_1/processPhase1.integration.test.ts, packages/core/conductor-tasks/bichard_phase_1/processPhase1.ts, packages/core/conductor-tasks/bichard_phase_1/sendToPhase2.integration.test.ts, packages/core/conductor-tasks/common/lockS3File.integration.test.ts, packages/core/conductor-tasks/common/lockS3File.ts
Note: This hasn't been integrated into the workflow yet to avoid the workflows blocking until the task is deployed. Follow-up PR to come
How it works:
- S3 can have key:value tags on a file
- When we start processing a workflow, we check the file to make sure it hasn't already got a "locked" tag
- If it has we'll carry on and ignore it as it's already been processed
- If it hasn't we'll add one and continue
There is a small possibility of a race condition here, however whenever we've had multiple workflows being triggered they've been separated by ~30 seconds, so this window of a few milliseconds is extremely unlikely to impact us in our specific scenario
=> Implement task for more explicit locking in bichard phase 1

.circleci/continue_config.yml, package-lock.json, package.json, packages/conductor/build.js, packages/conductor/package.json, packages/core/package.json, packages/core/phase1/triggers/generate.ts, packages/core/phase1/triggers/index.ts
There is a vulnerability in esbuild, but we don't really need to be using that anyway if we use a two stage build. A few notes:
- I changed the trigger importing to remove the dynamic requires as this makes it hard to create a static build. It's probably safer and more explicit anyway to be honest
- I've changed the Circle CI job to run the worker in Docker now as running it standalone was always a workaround for the build time. This is good because we actually run the docker image in CI
- Also updated to use the latest version of `pretty-data` in core. This is used to pretty print the XML before comparing it in the comparison tests. It hasn't been updated for a while but the couple of commits since the release fix an esbuild failures. Since the comparison tests are time limited I haven't …
=> Use esbuild for Conductor and re-work the image to be two-stage

packages/core/comparison/lib/comparePhase1.ts, packages/core/comparison/lib/isIntentionalDifference/badManualMatch.ts, packages/core/comparison/lib/isIntentionalDifference/badlyAnnotatedSingleCaseMatch.ts, packages/core/comparison/lib/isIntentionalDifference/bichardMatchesRandomFinalOffence.ts, packages/core/comparison/lib/isIntentionalDifference/convictionDateMatching.ts, packages/core/comparison/lib/isIntentionalDifference/coreMatchesBichardAddsInCourt.ts, packages/core/comparison/lib/isIntentionalDifference/coreUsesManualMatchData.ts, packages/core/comparison/lib/isIntentionalDifference/doubleSpacesInNames.ts, packages/core/comparison/lib/isIntentionalDifference/fixedForce91.ts, packages/core/comparison/lib/isIntentionalDifference/fixedNumberOfOffencesTic.ts, packages/core/comparison/lib/isIntentionalDifference/ho100304WithExistingFinalOffence.ts, packages/core/comparison/lib/isIntentionalDifference/ho100310AndHo100332Equivalent.ts, packages/core/comparison/lib/isIntentionalDifference/ho100332NotHo100304.ts, packages/core/comparison/lib/isIntentionalDifference/ho100332WithConvictionDate.ts, packages/core/comparison/lib/isIntentionalDifference/ho100332WithSameResults.ts, packages/core/comparison/lib/isIntentionalDifference/ho100333AndCCRHasLeadingZero.ts, packages/core/comparison/lib/isIntentionalDifference/identicalOffenceSwitchedSequenceNumbers.ts, packages/core/comparison/lib/isIntentionalDifference/index.ts, packages/core/comparison/lib/isIntentionalDifference/invalidASN.ts, packages/core/comparison/lib/isIntentionalDifference/invalidManualSequenceNumber.ts, packages/core/comparison/lib/isIntentionalDifference/missingEmptyCcr.ts, packages/core/comparison/lib/isIntentionalDifference/nonMatchingManualSequenceNumber.ts, packages/core/comparison/lib/isIntentionalDifference/offenceReasonSequenceFormat.ts, packages/core/comparison/lib/isIntentionalDifference/prioritiseNonFinal.ts, packages/core/comparison/lib/isIntentionalDifference/trailingSpace.ts, packages/core/comparison/types/ComparisonData.ts
Atm, intentional differences for comparison tests are only used in Phase 1, however we want to use them for Phase 2 as well. The existing functions that check for these may be applicable for just Phase 1, or both.
This PR is in preparation for adding an intentional difference for Phase 2, related to #795.
> ⚠️ Warning: This PR is best reviewed using GitHub's hide whitespace feature for a more efficient and less confusing review!
- Add `checkIntentionalDifferenceForPhases` wrapper function that handles the checking of whether an intentional difference is applicable to the current phase testing, and refactor our current functions to use it.
- This approach was preferred over updating all the intentional differences functions with an if statement to provide a consistent way of handling this …
=> Update intentional differences to specify applicable phases

packages/core/comparison/lib/comparePhase2.ts, packages/core/comparison/lib/isIntentionalDifference/bichardRaisesHo200114ForNonExactSequenceNumbers.ts, packages/core/comparison/lib/isIntentionalDifference/index.ts, packages/core/comparison/lib/summariseMatching.ts
We ran the comparison tests for Phase 2, and it highlighted a failure where Bichard raised a HO200114 exception and Core didn't. Upon investigating, we realised that this was a bug in Bichard (see comments in intentional difference function). 
- Update Phase 2 comparison test to check for intentional differences. This will also fix whitespace failures when running the tests.
- Add a new intentional difference function to cover the case when Bichard incorrectly raises a HO200114.
=> Add Phase 2 intentional difference for Bichard incorrectly raising HO200114

packages/core/phase2/lib/deriveOperationSequence/handleSentence.test.ts, packages/core/phase2/lib/deriveOperationSequence/handleSentence.ts
When running Phase 2 comparison tests, there were a couple of failures around Core not raising HO200106 exceptions, but Bichard did.
Upon investigation, we realised that our rewrite logic (`/lib/deriveOperationSequence/handleSentence` function) for `UpdateMessageSequenceBuilderImpl.java:1153` (the `deriveOperationSequence` function) didn't quite match up, and we were retuning early when adjudication don't exist.
Fix the `handleSentence` function to match Bichard, and update unit tests. We removed one as that was testing for the incorrect early return.
=> Fix HO200106 exception not being raised in handleSentence function

packages/core/phase2/lib/deriveOperationSequence/handleSentence.test.ts, packages/core/phase2/lib/deriveOperationSequence/handleSentence.ts, packages/core/types/DocumentType.ts
PR to remove code related to checking the document type. We only receive and process SPI Results.
=> Remove document type check in Phase 2

packages/core/comparison/cli/getComparisonStatistics.test.ts, packages/core/comparison/cli/getComparisonStatistics.ts, packages/core/comparison/cli/printResult.ts, packages/core/phase1/serialise/ahoXml/addAhoErrors.test.ts, packages/core/phase1/serialise/ahoXml/addAhoErrors.ts, packages/core/phase1/serialise/ahoXml/addExceptionsToAhoXml.ts
From running the Phase 2 comparison tests, there were a couple of XML output failures with `Result hasError="true"` being set by Core, but not on Bichard.
- Fix `hasError` attribute on a `Result` for Phase 2 to match Bichard.
- I've run the comparison tests for Phase 1 and 2, and either green or expected failures due to standing data version. 
- Output the number of passing PncUpdateDatasets for the comparison tests.
=> Fix hasError attribute on a Result for Phase 2

packages/core/phase1/enrichAho/enrichFunctions/matchOffencesToPnc/offenceHasFinalResult.ts, packages/core/phase1/schemas/pncQueryResult.ts, packages/core/phase1/serialise/ahoXml/serialiseToXml.ts, packages/core/phase1/tests/helpers/mockRecordInPnc.ts, packages/core/phase2/addRemandOperation.ts, packages/core/phase2/allPncOffencesContainResults.ts, packages/core/phase2/areAllResultsAlreadyPresentOnPnc.ts, packages/core/phase2/checkNoSequenceConditions.ts, packages/core/phase2/createPncAdjudication.ts, packages/core/phase2/createPncDisposal.test.ts, packages/core/phase2/createPncDisposal.ts, packages/core/phase2/disqualifiedFromKeepingDisposalText.test.ts, packages/core/phase2/disqualifiedFromKeepingDisposalText.ts, packages/core/phase2/exclusionOrderDisposalText.test.ts, packages/core/phase2/exclusionOrderDisposalText.ts, packages/core/phase2/getDisposalTextFromResult.test.ts, packages/core/phase2/getDisposalTextFromResult.ts, packages/core/phase2/getOperationSequence.ts, packages/core/phase2/incompatibleOperationCode.ts, packages/core/phase2/isMatchToPncAdj.ts, packages/core/phase2/isMatchToPncAdjAndDis.test.ts, packages/core/phase2/isMatchToPncDis.test.ts, packages/core/phase2/isPncDisposalMatch.test.ts, packages/core/phase2/isPncDisposalMatch.ts, packages/core/phase2/lib/getDisFromResult/createPncDisposalByFirstAndSecondDurations.test.ts, packages/core/phase2/lib/getDisFromResult/getDisFromResult.ts, packages/core/phase2/pncUpdateDataset/processPhase2PncUpdateDataset.ts, packages/core/phase2/tests/fixtures/helpers/generateFakePncUpdateDataset.ts
In this PR:
- removed force casting to `PncDisposal` in `createPncDisposal` function.
- updated `PncResultQuery` schema to make `type` and `sentenceDate` optional. In Phase 2, these values can be `undefined`.
- Simplified some of the Phase 2 regex expressions
- Refactored some of the Phase 2 functions
=> More phase 2 refactoring

packages/core/phase2/lib/getOperationSequence/validateOperationSequence/incompatibleOperationCode.test.ts, packages/core/phase2/lib/getOperationSequence/validateOperationSequence/incompatibleOperationCode.ts, packages/core/phase2/lib/getOperationSequence/validateOperationSequence/validateOperationSequence.test.ts
When running Phase 2 comparison tests, there were a couple of failures around Core not raising a HO200115 exception, but Bichard did.
- Fix `HO200115` exception not being raised in Phase 2 by ensuring that `SUBVAR` and `DISARR` come up as incompatible codes. A `HO200115` exception is raised when this is the case, see [incompatibleOperationExceptionCode.ts#L12-L20](https://github.com/ministryofjustice/bichard7-next-core/blob/ebbffacf80264ad6205dfffce6be48e334295eb5/packages/core/phase2/lib/getOperationSequence/validateOperationSequence/incompatibleOperationExceptionCode.ts#L12-L20).
- Update the unit tests for `incompatibleOperationCode` and add one for `validateOperationsSequence` for certainty as it uses `incompatibleOperationCode`.
https://dsdmoj.atlassian.net/browse/BICAWS7-2913
=> Fix HO200115 exception not being raised in Phase 2

packages/core/phase1/parse/parseAhoXml/__snapshots__/parseAhoXml.test.ts.snap, packages/core/phase1/parse/parseAhoXml/parseAhoXml.ts, packages/core/phase1/tests/fixtures/AnnotatedHO1.xml
When running Phase 2 comparison tests, we got a couple of failures on XML output if the title included double spaces e.g.
```
<ds:Title NameSequence="1"><ds:Title>Mr  and  Mrs</ds:Title></ds:GivenName>
<ds:Title NameSequence="1">Mr and Mrs</ds:Title>
```
- Remove double spaces for title when parsing XML.
https://dsdmoj.atlassian.net/browse/BICAWS7-2913
=> Fix double spaces within a title when parsing XML

packages/core/comparison/lib/isIntentionalDifference/ho200200AndMultilineResultVariableText.ts, packages/core/comparison/lib/isIntentionalDifference/index.ts
We recently improved Phase 2 Core to properly handle newline characters when extracting disposal text from the result variable text. This improvement led to failures in comparison tests where the old Bichard returned empty disposal text, while Core now returns multiline disposal text that sometimes exceeds the text length limit.
This PR introduces a filter for intentional differences to disregard this specific discrepancy.
=> Add a filter to intentional differences for HO200200

packages/conductor/e2e-test/bichardPhase1.e2e.test.ts, packages/conductor/e2e-test/helpers/e2eHelpers.ts, packages/conductor/workflows/bichard_phase_1.json
This wires the bichard_phase_1 workflow to use the task created in #797 - now we check to see if we can get a lock and if we can't or the file is already gone, we exit gracefully.
Should prevent the slack alerts complaining about failed workflows
=> Update the bichard_phase_1 workflow to use the s3 file locking task

packages/core/phase2/lib/getOperationSequence/areAllResultsAlreadyPresentOnPnc/isMatchToPncAdjAndDis/getDisFromResult/getDisposalTextFromResult/exclusionRequirementsDisposalText.test.ts, packages/core/phase2/lib/getOperationSequence/areAllResultsAlreadyPresentOnPnc/isMatchToPncAdjAndDis/getDisFromResult/getDisposalTextFromResult/exclusionRequirementsDisposalText.ts, packages/core/phase2/lib/getOperationSequence/areAllResultsAlreadyPresentOnPnc/isMatchToPncAdjAndDis/getDisFromResult/getDisposalTextFromResult/licencedPremisesExclusionOrderDisposalText.test.ts, packages/core/phase2/lib/getOperationSequence/areAllResultsAlreadyPresentOnPnc/isMatchToPncAdjAndDis/getDisFromResult/getDisposalTextFromResult/licencedPremisesExclusionOrderDisposalText.ts
When running Phase 2 comparison tests, there were a few failures where Core raises HO200104 exceptions but Bichard didn't.
It turns out that when checking if all court case offence results were already present on the PNC (`areAllResultsAlreadyPresentOnPnc`), Core was returning `false` and Bichard was returning `true`. This was because when checking if disposals match (`isPncDisposalMatch`) we check the disposal text but weren't able to match because it included double spaces. By returning `areAllResultsAlreadyPresentOnPnc === false`, we eventually cause a HO200104 exception. Bichard maintains the double spacing in the disposal text, therefore avoiding this problem.
- Update exclusion disposal texts to keep extra spaces in locations.
- Since `\s` is equivalent to `\r\n\t\f\v` and …
=> Update exclusion disposal texts to keep extra spaces in locations

packages/core/comparison/lib/comparePhase2.ts
This PR updates `comparePhase2` function to set the `hasError` to `false` in the output XML when all PNC operations are completed.
=> Set has error to false when all PNC operations are completed

package.json, scripts/post-install.sh
The post-install script was triggering itself due to the `npm i` command, resulting in an infinite loop. To resolve this issue, `--ignore-scripts` flag added to the npm command, preventing the post-install script from executing recursively.
=> Fix post-install script

environment/localstack/init/ready.d/setup.sh, packages/core/conductor-tasks/common/lockS3File.integration.test.ts, packages/core/conductor-tasks/common/lockS3File.ts
This was throwing an error and still causing the failure to pop up in slack. Tried to add a test but localstack behaves differently to AWS in this edge case. I've opened a bug report for localstack here: https://github.com/localstack/localstack/issues/11180
=> Handle locking when s3 file has a delete marker

packages/core/phase2/lib/addRemandOperation.test.ts, packages/core/phase2/lib/addRemandOperation.ts, packages/core/phase2/lib/isDefendantWarrantIssuedResult.ts
This function is unnecessary and can be inlined where it is only used in `addRemandOperation.ts`.
https://dsdmoj.atlassian.net/browse/BICAWS7-2963
=> Refactor out need for isDefendantWarrantIssuedResult function

packages/core/phase2/lib/getOperationSequence/areAllResultsAlreadyPresentOnPnc/isMatchToPncAdjAndDis/allRecordableResultsMatchAPncDisposal.test.ts, packages/core/phase2/lib/getOperationSequence/areAllResultsAlreadyPresentOnPnc/isMatchToPncAdjAndDis/allRecordableResultsMatchAPncDisposal.ts, packages/core/phase2/lib/getOperationSequence/areAllResultsAlreadyPresentOnPnc/isMatchToPncAdjAndDis/isMatchToPncAdjAndDis.test.ts, packages/core/phase2/lib/getOperationSequence/areAllResultsAlreadyPresentOnPnc/isMatchToPncAdjAndDis/isMatchToPncAdjAndDis.ts
In this PR:
- Fixed `isMatchToPncAdjAndDis` to return exceptions
- Added tests to check exceptions are returned
=> Fix isMatchToPncAdjAndDis to return exceptions

packages/core/phase2/lib/getOperationSequence/deriveOperationSequence/deriveOperationSequence.test.ts, packages/core/phase2/lib/getOperationSequence/deriveOperationSequence/deriveOperationSequence.ts, packages/core/phase2/lib/getOperationSequence/deriveOperationSequence/resultClassHandlers/handleAdjournmentPostJudgement.test.ts, packages/core/phase2/lib/getOperationSequence/deriveOperationSequence/resultClassHandlers/handleAdjournmentPostJudgement.ts, packages/core/phase2/lib/getOperationSequence/deriveOperationSequence/resultClassHandlers/handleAdjournmentPreJudgement.test.ts, packages/core/phase2/lib/getOperationSequence/deriveOperationSequence/resultClassHandlers/handleAdjournmentPreJudgement.ts, packages/core/phase2/lib/getOperationSequence/deriveOperationSequence/resultClassHandlers/handleAdjournmentWithJudgement.test.ts, packages/core/phase2/lib/getOperationSequence/deriveOperationSequence/resultClassHandlers/handleAppealOutcome.test.ts, packages/core/phase2/lib/getOperationSequence/deriveOperationSequence/resultClassHandlers/handleAppealOutcome.ts, packages/core/phase2/lib/getOperationSequence/deriveOperationSequence/resultClassHandlers/handleJudgementWithFinalResult.test.ts, packages/core/phase2/lib/getOperationSequence/deriveOperationSequence/resultClassHandlers/handleJudgementWithFinalResult.ts, packages/core/phase2/lib/getOperationSequence/deriveOperationSequence/resultClassHandlers/handleSentence.test.ts, packages/core/phase2/lib/getOperationSequence/deriveOperationSequence/resultClassHandlers/handleSentence.ts, packages/core/phase2/tests/helpers/generateResultClassHandlerParams.ts
The parameters of `resultClassHandler` functions in the `deriveOperationSequence` function take in things that could be found using other parameters and some of which are not used in all the functions which unnecessarily bloats the function call.
- Remove `fixedPenalty`, `adjudicationExists`, `pncDisposalCode` and `contains2007Result` of resultClassHandler functions and their tests.
- We intend to remove some more but this PR specifically targets the "low-hanging fruit" ones and tries to avoid a big boi PR with too many changes.
- Extract out and add `generateResultClassHandlerParams` helper function for unit tests.
https://dsdmoj.atlassian.net/browse/BICAWS7-2982
=> Remove unnecessary parameters of resultClassHandler functions

scripts/generate-schema-doc.sh
This is breaking the pipeline for deploying the Architecture and Docs website.
https://github.com/ministryofjustice/bichard7-next-core/actions/runs/10037285080/job/27736747583
=> Fix schema import paths in generate-schema-doc.sh script

packages/core/phase2/lib/getOperationSequence/deriveOperationSequence/deriveOperationSequence.test.ts, packages/core/phase2/lib/getOperationSequence/deriveOperationSequence/deriveOperationSequence.ts, packages/core/phase2/lib/getOperationSequence/deriveOperationSequence/resultClassHandlers/handleAdjournment.test.ts, packages/core/phase2/lib/getOperationSequence/deriveOperationSequence/resultClassHandlers/handleAdjournment.ts, packages/core/phase2/lib/getOperationSequence/deriveOperationSequence/resultClassHandlers/handleAdjournmentPostJudgement.test.ts, packages/core/phase2/lib/getOperationSequence/deriveOperationSequence/resultClassHandlers/handleAdjournmentPostJudgement.ts, packages/core/phase2/lib/getOperationSequence/deriveOperationSequence/resultClassHandlers/handleAdjournmentPreJudgement.test.ts, packages/core/phase2/lib/getOperationSequence/deriveOperationSequence/resultClassHandlers/handleAdjournmentPreJudgement.ts, packages/core/phase2/lib/getOperationSequence/deriveOperationSequence/resultClassHandlers/handleAdjournmentWithJudgement.test.ts, packages/core/phase2/lib/getOperationSequence/deriveOperationSequence/resultClassHandlers/handleAdjournmentWithJudgement.ts, packages/core/phase2/lib/getOperationSequence/deriveOperationSequence/resultClassHandlers/handleAppealOutcome.test.ts, packages/core/phase2/lib/getOperationSequence/deriveOperationSequence/resultClassHandlers/handleAppealOutcome.ts, packages/core/phase2/lib/getOperationSequence/deriveOperationSequence/resultClassHandlers/handleJudgementWithFinalResult.test.ts, packages/core/phase2/lib/getOperationSequence/deriveOperationSequence/resultClassHandlers/handleJudgementWithFinalResult.ts, packages/core/phase2/lib/getOperationSequence/deriveOperationSequence/resultClassHandlers/handleSentence.test.ts, packages/core/phase2/lib/getOperationSequence/deriveOperationSequence/resultClassHandlers/handleSentence.ts, packages/core/phase2/tests/helpers/generateResultClassHandlerParams.ts
The parameters of `resultClassHandler` functions in the `deriveOperationSequence` function take in things that could be found using other parameters and some of which are not used in all the functions which unnecessarily bloats the function call.
- Remove `ccrId` of resultClassHandler functions and update their tests.
https://dsdmoj.atlassian.net/browse/BICAWS7-2982
=> Remove ccrId from parameter from resultClassHandler functions

packages/core/phase2/lib/getOperationSequence/generateOperations/createRemandOperation.test.ts, packages/core/phase2/lib/getOperationSequence/generateOperations/createRemandOperation.ts, packages/core/phase2/lib/getOperationSequence/generateOperations/filterDisposalsAddedInCourt.test.ts, packages/core/phase2/lib/getOperationSequence/generateOperations/filterDisposalsAddedInCourt.ts, packages/core/phase2/lib/getOperationSequence/generateOperations/resultClassHandlers/handleAdjournmentWithJudgement.test.ts
We ran Phase 2 comparison tests and it came back with a number of failures related to a number of refactorings we've done recently.
- Update `createRemandOperation` to always set CCR and `isAdjournmentPreJudgement`.
- I think the issue is related to the fact we moved these attribute out of the `data` attribute of an operation and therefore weren't setting it when `data` was undefined when we needed it.
- Update `filterDisposalsAddedInCourt` to sort operations to always have disposals added in court at the end of the list.
- Due to the mutation of operations previously implemented, ordering matters and it just so happened that disposals added in court are added last.
=> Fix Phase 2 comparison tests

.circleci/continue_config.yml, environment/docker-compose-worker.yml, environment/local-conductor-worker.env, package.json, packages/common/test/conductor/waitForCompletedWorkflow.ts, packages/conductor/README.md, packages/conductor/e2e-test/bichardPhase2.e2e.test.ts, packages/conductor/e2e-test/fixtures/phase2/success-aho.json, packages/conductor/src/worker.ts, packages/conductor/tasks/persist_phase2.json, packages/conductor/tasks/process_phase2.json, packages/conductor/tasks/send_to_phase3.json, packages/conductor/workflows/bichard_phase_2.json, packages/core/conductor-tasks/bichard_phase_1/sendToPhase2.integration.test.ts, packages/core/conductor-tasks/bichard_phase_1/sendToPhase2.ts, packages/core/conductor-tasks/bichard_phase_2/processPhase2.ts, packages/core/conductor-tasks/bichard_phase_2/sendToPhase3.ts, packages/core/phase2/phase2.ts
We use legacy Bichard for Phase 2 of messaging processing but since we've completed rewriting Phase 2 in Core (with some Great Refactoring™️ still in-progress), we can now start to get it running in Conductor like Phase 1.
- Create a new Conductor workflow and tasks for Phase 2.
- We've duplicated the setup for Phase 1 and changed a few things for Phase 2 with the intention to refactor some things later.
- We've skipped some tests as a lot of them require persistence which we've not implemented yet.
- Update `sendToPhase2` task for Phase 1 workflow to either send messages to MQ (legacy Bichard) or Conductor depending on `PHASE2_CORE_CANARY_RATIO` environment variable.
- This defaults to 0 so send all to legacy Bichard for Phase 2.
https://dsdmoj.atlassian.net/browse/BICAWS7-2993
=> Create Phase 2 Conductor workflow and tasks

packages/core/phase2/phase2.test.ts, packages/core/phase2/phase2.ts
Atm, we're always returning a successful result type for our main Phase 2 function.
- Update `phase2` to return `Phase2ResultType.success`, `Phase2ResultType.exceptions` or `Phase2ResultType.ignored`.
- Add tests for `phase2` to cover checking the result type.
- As there was not a lot of existing test coverage for the function and I had no confidence I understood what the hell was going on, I did my best to write unit tests first to cover the existing return of result type based on the route it takes through `processMessage` and then only change it. The commits should tell the bumpy and long road I took.
- I've run the comparison tests covering a couple of days here and there and all green.
https://dsdmoj.atlassian.net/browse/BICAWS7-3015
=> Update Phase 2 to return correct result type

.circleci/config.yml, .circleci/continue_config.yml
We've just started adding Phase 2 characterisation tests. This caused them to [fail on main as the CircleCI job that runs Node 16](https://app.circleci.com/pipelines/github/ministryofjustice/bichard7-next-core/5115/workflows/9ad232d5-b8ab-429f-8b1b-b23b2bbfe367/jobs/36904) which doesn't include `structuredClone`.
- Update characterisation tests to use same image as other CircleCI jobs which is Ubuntu.
- Update CircleCI to always run jobs if CircleCI config changes.
- This can easily lead to the mistake of thinking that if CI is green when a job in the config has changed but it doesn't actually run because there were no changes in a package.
=> Update characterisation tests to use same image as other CircleCI jobs

.circleci/continue_config.yml
This was pinned on 0.3.1 but the [latest version is 1.1.0](https://www.npmjs.com/package/wait-port). In our tests repo, we don't pin a version of this and haven't experienced any flakiness, but in Core we have.
=> Remove pinned version for wait-port for characterisation tests in CI

packages/core/lib/parse/parseAhoXml/__snapshots__/parseAhoXml.test.ts.snap, packages/core/lib/parse/parseAhoXml/parseAhoXml.ts, packages/core/phase1/tests/fixtures/AnnotatedHO1.xml, packages/core/types/AhoXml.ts
For HO200201, it is raised when an offence result has a `ResultQualifierVariable` which has a `Duration`.
Whilst writing a characterisation test for HO200201, we noticed that this exception would raise for legacy Bichard but not Core.
This is because for Core when we parse the XML for an input message, we’re ignoring it, although it's defined in `resultQualifierVariableSchema`.
- Update `parseAhoXml` to include `Duration` for `ResultQualifierVariable`.
- This will ensure we can raise a HO200201 in [validateResultQualifierVariableDurationType](https://github.com/ministryofjustice/bichard7-next-core/blob/e0d53234f4c85e5370520af92b8d0ec95811b8b3/packages/core/phase2/lib/getOperationSequence/areAllResultsAlreadyPresentOnPnc/isMatchToPncAdjAndDis/getDisFromResult/validateResultQualifierVariable …
=> Update parseAhoXml to include Duration for ResultQualifierVariable

packages/core/lib/isAdjournedNoNextHearing.ts, packages/core/phase1/enrichAho/enrichFunctions/enrichOffenceResultsPostPncEnrichment/populateResultClass.ts, packages/core/phase2/lib/getOperationSequence/generateOperations/createRemandOperation.test.ts, packages/core/phase2/lib/getOperationSequence/generateOperations/createRemandOperation.ts
Function isAdjournedNoNextHearing always returned false. It is rendered redundant where implemented.
=> BICAWS7-2978 - remove isAdjournedNoNextHearing

packages/core/phase2/phase2.test.ts, packages/core/phase2/phase2.ts
In legacy Bichard, we only check for AINT case for AHOs:
https://github.com/ministryofjustice/bichard7-next/blob/main/bichard-backend/src/main/java/uk/gov/ocjr/mtu/br7/pnc/update/manager/PNCUpdateChoreographyHO.java#L158
By not having this, we incorrectly generate triggers such as TRPS0004.
https://dsdmoj.atlassian.net/browse/BICAWS7-3029
=> Update Phase 2 condition to only check for AINT case for AHO

packages/message-forwarder/src/forwardMessage/forwardMessage.auto.integration.test.ts, packages/message-forwarder/src/forwardMessage/forwardMessage.conductor.integration.test.ts, packages/message-forwarder/src/forwardMessage/forwardMessage.ts, packages/message-forwarder/src/forwardMessage/forwardMessage.unit.test.ts, packages/message-forwarder/src/forwardMessage/sendToResubmissionQueue/sendToResubmissionQueue.ts, packages/message-forwarder/src/forwardMessage/sendToResubmissionQueue/sendToResubmissionQueue.unit.test.ts, packages/message-forwarder/src/forwardMessage/startBichardProcess/startBichardProcess.integration.test.ts, packages/message-forwarder/src/forwardMessage/startBichardProcess/startBichardProcess.ts, packages/message-forwarder/src/test/fixtures/pnc-update-dataset.xml
In Phase 2, an AHO or PncUpdateDataset can be received. The message forwarder only expects to parse an AHO atm.
- Update forwardMessage to parse PncUpdateDataset as well.
- The PncUpdateDataset is a copy of [PncUpdateDataSet-no-operations.xml](https://github.com/ministryofjustice/bichard7-next-core/blob/main/packages/core/phase2/tests/fixtures/PncUpdateDataSet-no-operations.xml) test fixture but with `CORRELATION_ID` to be replaced.
- This did give me the idea that we should consider taking the same approach as we do in our characterisation tests and create or share a `generatePhase2Message` function. Shall I create a ticket in our backlog? There would be a number of files to remove and tests to update which is why it's not been done in this PR.
- Refactor `CONDUCTOR_WORKFLOW` to use an …
=> Update message forwarder to parse PncUpdateDataset as well

environment/docker-compose-bichard.yml
In #936, I forgot to update the Docker Compose for legacy Bichard with the Phase 2 message forwarder which meant that CI in UI broke as it uses legacy Bichard as the backend i.e. uses `npm run all-legacy` command.
=> Update Docker Compose for legacy Bichard with Phase 2 message forwarder

packages/common/conductor/middleware/s3TaskDataFetcher.ts, packages/core/conductor-tasks/bichard_phase_1/sendToPhase2.integration.test.ts, packages/core/conductor-tasks/bichard_phase_1/sendToPhase2.ts
This PR updates the Send to Phase 2 conductor task to allow the `phase2CanaryRatio` input parameter to override the default `PHASE2_CORE_CANARY_RATIO` environment variable. If the `phase2CanaryRatio` input parameter is provided and its value is not `-1`, it will be used instead of the environment variable.  This change is part of the Phase 2 migration plan and introduces a temporary parameter for testing the Phase 2 conductor workflow.
```json
{
"tasks": [
...
{
"name": "send_to_phase2",
"taskReferenceName": "send_to_phase2",
"inputParameters": {
"s3TaskDataPath": "${workflow.input.s3TaskDataPath}",
"options": {
"phase2CanaryRatio": -1
}
},
"type": "SIMPLE",
"startDelay": 0,
"optional": false,
"asyncComplete": false,
"permissive": false
},
...
]
}
```
Initially, we considered using …
=> Update send to Phase2 task to override canary ratio value

packages/core/phase2/exceptions/HO200110.test.ts, packages/core/phase2/exceptions/HO200110.ts, packages/core/phase2/exceptions/HO200212.ts, packages/core/phase2/exceptions/generateExceptions.ts, packages/core/phase2/lib/getOperationSequence/checkNoSequenceConditions.test.ts, packages/core/phase2/lib/getOperationSequence/checkNoSequenceConditions.ts, packages/core/phase2/phase2.ts
In this PR:
- Added `HO200110.ts`
- Updated `phase2.ts` to check generated exceptions for early return
- Removed old HO200110 code
- Added an empty function for `HO200212`
- Updated `generateExceptions` function to return early if:
- `HO200212` is generated
- `HO200110`, `HO200116`, or `HO200117` are generated
=> Add HO200110

packages/core/phase2/lib/generateOperations/__snapshots__/validateOperations.test.ts.snap, packages/core/phase2/lib/generateOperations/generateOperations.ts, packages/core/phase2/lib/generateOperations/validateOperations.test.ts, packages/core/phase2/lib/generateOperations/validateOperations.ts
`extractRemandCcrs` is not used anywhere else within the `generateOperations` function so can be moved into `validateOperations` where it is used.
- Move `extractRemandCcrs` into `validateOperations` so we remove the parameter and calling it in `generateOperations`.
- Fix the `validateOperations` tests.
- Only add remandCcr when there's a remand operation as per `extractRemandCcrs` logic.
- Update snapshot as adding the remandCcrs when there wasn't a remand operation meant that we were returning the wrong exception. (I've the comparison tests and so far all good so I think the test is wrong.)
https://dsdmoj.atlassian.net/browse/BICAWS7-2990
=> Move extractRemandCcrs into validateOperations

packages/core/phase2/lib/generateOperations/__snapshots__/validateOperations.test.ts.snap, packages/core/phase2/lib/generateOperations/generateOperations.ts, packages/core/phase2/lib/generateOperations/validateOperations.test.ts, packages/core/phase2/lib/generateOperations/validateOperations.ts
In #972, we moved `extractRemandCcrs` into `validateOperations`. Comparison tests were run but it turns out the tests run didn't cover when duplicate remand operations are created which could all have different CCRs and needed within `validateOperations`. (One example was found after I was looking into refactoring inside the `validateOperations` which proved this isn't a refactoring... 😭)
- Move back `extractRemandCcrs` into `generateOperations`.
- The `validateOperations` tests are still incorrect though. Checking the [OPERATION_COMBINATION_ERRORS](https://github.com/ministryofjustice/bichard7-next/blob/bc722a0e8a7f857a6d22caaab4c9743000154d78/bichard-backend/src/main/java/uk/gov/ocjr/mtu/br7/pnc/message/builder/impl/UpdateMessageSequenceBuilderImpl.java#L79) in legacy Bichard shows that …
=> Move extractRemandCcrs back into generateOperations

packages/core/lib/triggers/TRPS0004.ts, packages/core/phase2/lib/areNewremTypesEqual.test.ts, packages/core/phase2/lib/areRemandOperationsEqual.ts, packages/core/phase2/lib/generateOperations/checkCaseRequiresRccButHasNoReportableOffences.ts, packages/core/phase2/lib/generateOperations/createRemandOperation.test.ts, packages/core/phase2/lib/generateOperations/createRemandOperation.ts, packages/core/phase2/lib/generateOperations/deduplicateOperations.test.ts, packages/core/phase2/lib/generateOperations/resultClassHandlers/handleAdjournment.ts, packages/core/phase2/lib/generateOperations/resultClassHandlers/handleAdjournmentPostJudgement.ts, packages/core/phase2/lib/generateOperations/resultClassHandlers/handleAdjournmentPreJudgement.ts, packages/core/phase2/lib/generateOperations/resultClassHandlers/handleAdjournmentWithJudgement.ts, packages/core/phase2/lib/refreshOperationSequence.ts, packages/core/types/PncUpdateDataset.ts
In this PR:
- refactored `createRemandOperation` function
- renamed Newrem to Remand
- refactored `checkCaseRequiresRccButHasNoReportableOffences`
=> Refactor createRemandOperation

packages/core/phase2/lib/generateOperations/__snapshots__/validateOperations.test.ts.snap, packages/core/phase2/lib/generateOperations/operationCourtCaseReference.ts, packages/core/phase2/lib/generateOperations/validateOperations.test.ts, packages/core/phase2/lib/generateOperations/validateOperations.ts
The current implementation for validating the PNC operations that are generated in Phase 2 are intertwined within a giant for loop. We're looking to extract separate files for each Phase 2 exception and so this aims to allow us to do that.
To refactor this function:
-  Legacy Bichard was referred to
- [the original `validateOperationSequence` function](https://github.com/ministryofjustice/bichard7-next/blob/df89f613d6dcbed261fe765a7ee612a2de952d46/bichard-backend/src/main/java/uk/gov/ocjr/mtu/br7/pnc/message/builder/impl/UpdateMessageSequenceBuilderImpl.java#L1417)
- [the "table" of invalid combination of operations](https://github.com/ministryofjustice/bichard7-next/blob/df89f613d6dcbed261fe765a7ee612a2de952d46/bichard-backend/src/main/java/uk/gov/ocjr/mtu/br7/pnc/message/builder/impl/Upd …
=> Refactor validateOperations function

.circleci/config.yml, .circleci/continue_config.yml
PR https://github.com/ministryofjustice/bichard7-next-core/pull/909 was created to help reduce CircleCI costs, however as it created from a fork, CircleCI couldn't run. We then recreated the PR in #915 but that became stale.
This PR recreates #915 with the latest changes from main as rebasing was too much effort for the easily replicable changes.
- Update CircleCI to dynamically set Docker layer caching (DLC) so it's only set when changes are made for jobs that require it.
=> Update CircleCI to dynamically set Docker layer caching

packages/core/phase2/exceptions/HO200113.test.ts, packages/core/phase2/exceptions/HO200113.ts, packages/core/phase2/exceptions/checkOperationsException.test.ts, packages/core/phase2/exceptions/checkOperationsException.ts, packages/core/phase2/lib/generateOperations/__snapshots__/validateOperations.test.ts.snap, packages/core/phase2/lib/generateOperations/generateOperations.test.ts, packages/core/phase2/lib/generateOperations/generateOperations.ts, packages/core/phase2/lib/generateOperations/validateOperations.ts
In #995, we refactored the `validateOperations` function to pull all of the logic out of the main for loop. This allows us to now follow what we've done with other Phase 2 exceptions and pull them out into their own exception generator function and file.
- Add HO200113 exception generator.
- Add `checkOperationsException`. This follows the pattern I saw with other exception generators.
- Update `validateOperations` to remove raising HO200113 and the `remandCcrs` parameter as it's only used for raising this exception. Also update `generateOperations` as a result of this change.
https://dsdmoj.atlassian.net/jira/software/c/projects/BICAWS7/boards/1368?selectedIssue=BICAWS7-3122
=> Add HO200113 exception generator

.github/workflows/format-code.yml
This fixes the `format-code` GitHub Actions workflow e.g. see https://github.com/ministryofjustice/bichard7-next-core/actions/runs/11325148575/job/31492529041 by using the latest version of the MOJ Code Formatter GitHub Action: to include this change https://github.com/ministryofjustice/github-actions/pull/275.
=> Update MOJ Code Formatter GitHub Action version

packages/core/phase2/exceptions/HO200112.test.ts, packages/core/phase2/exceptions/HO200112.ts, packages/core/phase2/exceptions/checkClashingCourtCaseOperationsException.test.ts, packages/core/phase2/exceptions/checkClashingCourtCaseOperationsException.ts, packages/core/phase2/exceptions/checkOperationsException.test.ts, packages/core/phase2/exceptions/checkOperationsException.ts, packages/core/phase2/lib/generateOperations/__snapshots__/validateOperations.test.ts.snap, packages/core/phase2/lib/generateOperations/validateOperations.test.ts, packages/core/phase2/lib/generateOperations/validateOperations.ts
In #995, we refactored the `validateOperations` function to pull all of the logic out of the main for loop. This allows us to now follow what we've done with other Phase 2 exceptions and pull them out into their own exception generator function and file.
- Add `checkClashingCourtCaseOperationsException` function.
- This will be used by HO200112, HO200115 and HO200114 exception generators. The logic has been lifted from `validateOperations` function.
- Add HO200112 exception generator.
- This uses `checkClashingCourtCaseOperationsException`.
- Update `validateOperations` function to no longer raise HO200112.
https://dsdmoj.atlassian.net/jira/software/c/projects/BICAWS7/boards/1368?selectedIssue=BICAWS7-3121
=> Add HO200112 exception generator

packages/core/phase2/exceptions/HO200115.test.ts, packages/core/phase2/exceptions/HO200115.ts, packages/core/phase2/lib/generateOperations/__snapshots__/validateOperations.test.ts.snap, packages/core/phase2/lib/generateOperations/validateOperations.ts
The check for penalty hearing and a disposal isn't included in the HO200115 exception generator because it's not possible to generate both at the same time.
https://dsdmoj.atlassian.net/jira/software/c/projects/BICAWS7/boards/1368?selectedIssue=BICAWS7-3124
=> Add HO200115 exception generator

packages/core/phase2/exceptions/HO200114.test.ts, packages/core/phase2/exceptions/HO200114.ts, packages/core/phase2/lib/generateOperations/__snapshots__/validateOperations.test.ts.snap, packages/core/phase2/lib/generateOperations/validateOperations.ts
The check for penalty hearing and a sentence deferred isn't included in the HO200114 exception generator because it's not possible to generate both at the same time.
https://dsdmoj.atlassian.net/jira/software/c/projects/BICAWS7/boards/1368?selectedIssue=BICAWS7-3123
=> Add HO200114 exception generator

packages/core/phase2/lib/generateOperations/generateOperations.test.ts, packages/core/phase2/lib/generateOperations/generateOperations.ts, packages/core/phase2/lib/generateOperations/resultClassHandlers/ResultClassHandler.ts, packages/core/phase2/lib/generateOperations/resultClassHandlers/handleAdjournmentWithJudgement.test.ts, packages/core/phase2/lib/generateOperations/resultClassHandlers/handleJudgementWithFinalResult.test.ts, packages/core/phase2/lib/generateOperations/resultClassHandlers/handleJudgementWithFinalResult.ts, packages/core/phase2/phase2.test.ts, packages/core/phase2/phase2.ts, packages/core/phase2/tests/helpers/generateResultClassHandlerParams.ts
- Update `generateOperations` function to pass in `areAllResultsOnPnc` so it only returns operations and not events.
- Update `phase2` function to call `areAllResultsOnPnc` and add ignored event if all results already on PNC.
https://dsdmoj.atlassian.net/browse/BICAWS7-2975
=> Refactor phase2 and generateOperations functions

packages/core/comparison/lib/isIntentionalDifference/ho200114InsteadOfHo200113.ts, packages/core/comparison/lib/isIntentionalDifference/index.ts, packages/core/comparison/lib/summariseMatching.ts
We ran Phase 2 comparison tests and had two failures where Core raised HO200114 but Bichard raised HO200113. This was expected as we recently refactored the exceptions that get raised when there are an invalid combination of operations generated. These exceptions get added to the ASN which means there can only be one set. We've decided that the order doesn't really matter in this case so an intentional difference is added.
- Add intentional difference for when Core raises HO200114 and Bichard raises HO200113 instead.
- I debugged the two comparison tests to make sure HO200113 was still generated and HO200114 just overrode it on the ASN.
=> Add intentional difference for HO200114 over HO200113

packages/conductor/workflows/bichard_phase_1.json, packages/core/comparison/lib/comparePhase2.ts, packages/core/conductor-tasks/bichard_phase_2/processPhase2.integration.test.ts, packages/core/phase2/phase2.ts
PR to:
- Remove redundant submitted to phase 3 event
- Set `phase2CanaryRatio` to `-1` in `send_to_phase2` task
- `phase2CanaryRatio` input parameter overrides `PHASE2_CORE_CANARY_RATIO` environment variable.
- `-1` means don't override `PHASE2_CORE_CANARY_RATIO`
=> Remove redundant submitted to phase 3 event

packages/core/phase2/exceptions/HO200101.ts, packages/core/phase2/exceptions/HO200104.ts, packages/core/phase2/exceptions/HO200108.test.ts, packages/core/phase2/lib/areAllPncDisposalsWithType.test.ts, packages/core/phase2/lib/areAllPncDisposalsWithType.ts, packages/core/phase2/lib/areAllPncResults2007.test.ts, packages/core/phase2/lib/areAllPncResults2007.ts, packages/core/phase2/lib/areAnyPncDisposalsWithType.test.ts, packages/core/phase2/lib/areAnyPncDisposalsWithType.ts, packages/core/phase2/lib/areAnyPncResults2007.ts, packages/core/phase2/lib/generateOperations/resultClassHandlers/handleJudgementWithFinalResult.ts, packages/core/phase2/lib/generateOperations/resultClassHandlers/handleSentence.test.ts, packages/core/phase2/lib/generateOperations/resultClassHandlers/handleSentence.ts
These are the original functions in legacy Bichard: [areAllPNCResults2007](https://github.com/ministryofjustice/bichard7-next/blob/2ace0ab64c93da6d76342b1b529f14c3c906a1aa/bichard-backend/src/main/java/uk/gov/ocjr/mtu/br7/pnc/message/builder/impl/UpdateMessageSequenceBuilderImpl.java#L438) and [areAnyPNCResults2007](https://github.com/ministryofjustice/bichard7-next/blob/2ace0ab64c93da6d76342b1b529f14c3c906a1aa/bichard-backend/src/main/java/uk/gov/ocjr/mtu/br7/pnc/message/builder/impl/UpdateMessageSequenceBuilderImpl.java#L491). This PR aims to address feedback in a previous PR: https://github.com/ministryofjustice/bichard7-next-core/pull/1054#discussion_r1819106244.
- Update `areAllPncResults2007` and `areAnyPncResults2007` to be generic functions and therefore rename them to …
=> Update areAllPncResults2007 and areAnyPncResults2007 to be generic functions

packages/core/phase2/exceptions/checkResultsMatchingPncDisposalsExceptions.ts, packages/core/phase2/lib/areAllResultsOnPnc.test.ts, packages/core/phase2/lib/areAllResultsOnPnc.ts, packages/core/phase2/lib/areResultsMatchingAPncDisposal.test.ts, packages/core/phase2/lib/areResultsMatchingAPncDisposal.ts, packages/core/phase2/lib/areResultsMatchingPncAdjudication.test.ts, packages/core/phase2/lib/areResultsMatchingPncAdjudication.ts, packages/core/phase2/lib/areResultsMatchingPncAdjudicationAndDisposals.test.ts, packages/core/phase2/lib/areResultsMatchingPncAdjudicationAndDisposals.ts, packages/core/phase2/lib/findPncCourtCase.ts, packages/core/phase2/lib/isMatchToPncAdjudication.test.ts, packages/core/phase2/lib/isMatchToPncAdjudication.ts, packages/core/phase2/lib/isMatchToPncAdjudicationAndDisposals.test.ts, packages/core/phase2/lib/isMatchToPncAdjudicationAndDisposals.ts, packages/core/phase2/lib/isResultMatchingAPncDisposal.test.ts, packages/core/phase2/lib/isResultMatchingAPncDisposal.ts
The logic of the functions used by `areAllResultsOnPnc` and `checkResultsMatchingPncDisposalsExceptions` are virtually the same apart from the fact that a `checkExceptionFn` function is passed in. From a long-term maintainability standpoint I think it's better that the duplication of logic is removed.
- Update `areAllResultsOnPnc` and `checkResultsMatchingPncDisposalsExceptions` and the underlying functions used.
- Remove duplicated logic in places.
- Moved logic in places e.g. some shared logic from `areAllResultsOnPnc` and `checkResultsMatchingPncDisposalsExceptions` have been moved into `areResultsMatchingPncAdjudicationAndDiposals` (was `isMatchToPncAdjudicationAndDisposals`) as they both use that function.
- Rename some functions for consistency.
- Reorder some function parameters …
=> Update areAllResultsOnPnc and checkResultsMatchingPncDisposalsExceptions

packages/common/db/baseConfig.ts
Also, remove unused DB_AUTH environment variables.
This caused `UNABLE_TO_GET_ISSUER_CERT_LOCALLY` errors in UI.
Related to https://github.com/ministryofjustice/bichard7-next-core/pull/1059.
=> Update DB_SSL in base config for database

packages/ui/cypress/e2e/case-details/lock-cases.cy.ts, packages/ui/cypress/e2e/case-details/view-case-details/view-resolution-status.cy.ts, packages/ui/src/services/listCourtCases.ts, packages/ui/test/services/listCourtCases/filterCasesByResolvedDate.integration.test.ts, packages/ui/test/services/listCourtCases/listCourtCases.integration.test.ts
**Current behavior:** 
For example,
The case has exception HO100304 and a trigger TRPR0001.
The exception HO100304 is resolved and trigger TRPR0001 is excluded for my user profile. 
When I log in as a supervisor (who has access to all), I can still see the case on new Bichard even though the **Resolved** filter is not set. However, the case no longer has any exceptions—as they have been resolved—and it doesn't have any triggers because TRPR0001 is excluded. 
**Fix:**
Modify the query to retrieve cases according to their status and user excluded triggers.
=> Retrieve cases according to case status and excluded triggers

.circleci/continue_config.yml, .circleci/scripts/ui-scripts/run-cypress-e2e-tests.sh, package-lock.json, packages/e2e-test/features/010a-nppa-exceptions/test.feature, packages/e2e-test/features/010b-nppa-ignored-results/test.feature, packages/e2e-test/features/011a-nppa-redirection/test.feature, packages/e2e-test/features/011b-nppa-ignored-results/test.feature, packages/e2e-test/features/034a-valid-asn-format/test.feature, packages/e2e-test/features/034b-valid-asn-format/test.feature, packages/e2e-test/features/109b-ignoring-breach-offence-dates/test.feature, packages/e2e-test/features/110a-psa_code_change/test.feature, packages/e2e-test/features/110b-psa_code_change/test.feature, packages/e2e-test/features/131a-sendef-newrem-combinations/test.feature, packages/e2e-test/features/131b-sendef-newrem-combinations/test.feature, packages/e2e-test/features/412-bichard-switching/old-bichard-user.feature, packages/e2e-test/features/603-asn-update-for-HO100301-nextui/test.feature, packages/e2e-test/features/604-display-only-unresolved-cases-when-filtering/test.feature, packages/e2e-test/features/701-next-hearing-location-bichard7/test.feature, packages/e2e-test/features/702-next-hearing-date-bichard/test.feature, packages/e2e-test/features/711-next-hearing-location-nextui/test.feature, packages/e2e-test/features/712-next-hearing-date-nextui/test.feature, packages/e2e-test/package.json, packages/e2e-test/scripts/add-filename-to-test-results-report.js, packages/e2e-test/scripts/run_test_chunk.sh
- Fix `split --split-by=timings` for cucumber tests
- Fix `split --split-by=timings` for cypress e2e tests
- Add a helper script to add the filename for the junit XML report
- Update features that didn't conform to our convention of putting the number of the test folder in the scenario 
- Resize the machines we were running on
1. Helps us save on credits
2. Helps us have an even (and hopefully quicker) cucumber and cypress runs
=> Add various tweaks to CircleCI

.circleci/continue_config.yml
- Reduce `xlarge` to `large` for Cucumber and Zap tests
- The Cypress component tests don't need docker UI image to run
The cost of `large` is: 20 credits/min
The cost of `xlarge` is: 100 credits/min
(The cost was last updated: September 26, 2024)
=> Reduce size of machines in CI

packages/ui/src/config.ts, packages/ui/src/pages/api/health.ts
- Keep the health endpoint free from things it doesn't care about
- Throw an error in config so the app won't start in prod if it has default env parameters
=> Refactor responsibility for verifying production has correct secrets

packages/ui/cypress/e2e/case-details/reallocate-case.cy.ts, packages/ui/cypress/e2e/case-details/view-case-details/view-notes.cy.ts, packages/ui/src/services/dto/courtCaseDto.ts
Notes are now displayed in descending date order
=> Notes should be displayed in the same order as old UI

.circleci/continue_config.yml, packages/e2e-test/helpers/MockPNCHelper.ts, packages/e2e-test/helpers/PNCTestTool.ts, packages/e2e-test/utils/auditLogging.ts, packages/e2e-test/utils/config.ts, packages/e2e-test/utils/healthCheck.ts, packages/e2e-test/utils/pnc.ts
- Better errors from `Poller` for `fetchMocks`
- Properly align the timeouts for Cucumber and `Poller` so that polling tasks don't timeout after the test they're executed from
=> Fix test timeouts

sonar-project.properties
Filter all fixtures and test files out of Sonar. Currently, Sonar is negatively reporting a lot of duplication in test files which is something we've decided we actively prefer as a team.
=> Filter out all test directories from Sonar

packages/ui/src/components/PhaseBanner/PhaseBanner.tsx
If you're on the feedback page and you click on the feedback link in the phase banner, the back link will break.
The following link:
=> Fix feedback in phase banner

packages/core/lib/PncGateway.ts
In the PNC API, the name of the header for the correlation ID is inconsistent across the API endpoints:
- `correlationId` for query endpoint
- `correlation-id` for all PNC operation endpoints
Our endgoal is to use `x-correlation-id` across all.
This is the first of a few PRs to gradually transition to a more consistent name.
=> Add new correlation ID header for PNC query

packages/ui/Dockerfile, packages/ui/docker/conf/supervisord.conf
This PR should unblock the pipeline which is currently failing because the UI service crashes in ECS. This happens because non-root users can't run services on privileged ports, and the container is configured to run nginx on 80/443.
Will attempt the non-root user directive again once Terraform allows us to map ports properly.
=> Run UI container as root user

packages/core/comparison/lib/comparePhase2.ts, packages/core/phase2/lib/getDisposalTextFromResult/getDisposalTextFromResult.test.ts, packages/core/phase2/lib/getDisposalTextFromResult/getDisposalTextFromResult.ts, packages/core/phase2/lib/getDisposalTextFromResult/isFailedToAppearWarrantIssued.test.ts, packages/core/phase2/lib/getDisposalTextFromResult/isFailedToAppearWarrantIssued.ts
This seems only necessary for TRPR0002 (which is now doing its own thing in its generator) but for getting the disposal text, only the result codes should be checked. 
See https://github.com/ministryofjustice/bichard7-next/blob/be3a080666a28a221496bd1cc75a6090ed1cb264/bichard-backend/src/main/java/uk/gov/ocjr/mtu/br7/pnc/message/disposal/impl/DisposalTextBuilderImpl.java#L123.
By checking the qualifiers, some Phase 3 comparison tests failed as Core was returning "" instead of "FAILED TO APPEAR WARRANT ISSUED". I've run some Phase 2 comparison tests as well.
=> Fix isFailedToAppearWarrantIssued for Phase 3

packages/core/phase3/lib/pncUpdateRequestGenerators/normalDisposalGenerator.ts
We had some Phase 3 comparison tests failures which showed we weren't correctly removing multiple spaces for `generatedPNCFilename` for PNC update requests for normal disposals. 
[We have a ticket around refactoring and adding tests for the normal disposal generator](https://dsdmoj.atlassian.net/browse/BICAWS7-3274).
=> Fix not removing multiple spaces for generated PNC filename in Phase 3

packages/core/lib/PncGateway.ts
We've updated the PNC API to accept `x-correlation-id` in legacy Bichard so we no longer need to send the deprecated header.
Related to https://github.com/ministryofjustice/bichard7-next/pull/880 and https://github.com/ministryofjustice/bichard7-next-core/pull/1186.
=> Remove redundant correlation ID headers in PNC gateway

packages/core/phase3/lib/hearingDetails/__snapshots__/createDisposalsFromOffence.test.ts.snap, packages/core/phase3/lib/hearingDetails/createDisposalsFromOffence.test.ts, packages/core/phase3/lib/hearingDetails/createDisposalsFromOffence.ts, packages/core/phase3/types/HearingDetails.ts
An attempt to make `createDisposalsFromOffence` function easier to read i.e. "less looking like legacy Bichard" (for reference, see [function in legacy Bichard](https://github.com/ministryofjustice/bichard7-next/blob/be3a080666a28a221496bd1cc75a6090ed1cb264/bichard-backend/src/main/java/uk/gov/ocjr/mtu/br7/pnc/message/factory/impl/DISSegmentFactoryImpl.java#L89)).
There are a lot of commits due to the refactoring approach taken. Samples of comparison tests were run after each atomic change.
https://dsdmoj.atlassian.net/browse/BICAWS7-3273
=> Refactor createDisposalsFromOffence function

.github/workflows/sonarqube.yml
sonarcloud-github-action will be deprecated very soon and replaced with sonarqube-scan-action.
https://github.com/SonarSource/sonarcloud-github-action/releases
https://github.com/SonarSource/sonarqube-scan-action
=> Change SonarCloud GitHub Action and version

packages/api/src/endpoints/versionedEndpoints.ts, packages/api/src/plugins/v1/health/plugin.e2e.test.ts, packages/api/src/plugins/v1/health/plugin.integration.test.ts, packages/api/src/plugins/v1/health/plugin.ts, packages/api/src/routes/v1/cases/case.integration.test.ts, packages/api/src/routes/v1/cases/case.ts, packages/api/src/routes/v1/cases/resubmit.e2e.test.ts, packages/api/src/routes/v1/cases/resubmit.integration.test.ts, packages/api/src/routes/v1/cases/resubmit.ts, packages/api/src/routes/v1/me.e2e.test.ts, packages/api/src/routes/v1/me.integration.test.ts, packages/api/src/routes/v1/me.ts, packages/api/src/server/auth/authenticate.e2e.test.ts, packages/api/src/server/auth/authenticate.integration.test.ts
Instead of having to write `VersionedEndpoints.V1.Case` we can write `V1.Case`
=> Refactor VersionedEndpoints to be simpler

packages/core/phase3/lib/getPncCourtCode.test.ts, packages/core/phase3/lib/getPncCourtCode.ts, packages/core/phase3/lib/pncUpdateRequestGenerators/disposalUpdatedGenerator.test.ts, packages/core/phase3/lib/pncUpdateRequestGenerators/disposalUpdatedGenerator.ts, packages/core/phase3/lib/pncUpdateRequestGenerators/normalDisposalGenerator/normalDisposalGenerator.test.ts, packages/core/phase3/lib/pncUpdateRequestGenerators/normalDisposalGenerator/normalDisposalGenerator.ts, packages/core/phase3/lib/pncUpdateRequestGenerators/penaltyHearingGenerator.test.ts, packages/core/phase3/lib/pncUpdateRequestGenerators/penaltyHearingGenerator.ts, packages/core/phase3/lib/pncUpdateRequestGenerators/remandGenerator/remandGenerator.ts, packages/core/phase3/lib/pncUpdateRequestGenerators/sentenceDeferredGenerator.test.ts, packages/core/phase3/lib/pncUpdateRequestGenerators/sentenceDeferredGenerator.ts
This PR removes the check and error handling for non-numeric third-level PSA codes. These codes are already validated as numbers in the standing data package.
=> Remove logic to check and throw error when third-level PSA code is not a number

packages/core/comparison/lib/comparePhase3.ts, packages/core/jest.config.js, packages/core/jest.setup.ts, packages/core/lib/exceptions/generatePncExceptionFromMessage.ts, packages/core/package.json, packages/core/phase1/tests/jest.d.ts, packages/core/phase1/tests/jest.setup.ts, packages/core/phase3/exceptions/generatePncUpdateExceptionFromMessage.test.ts, packages/core/phase3/exceptions/generatePncUpdateExceptionFromMessage.ts, packages/core/phase3/lib/performOperations.test.ts, packages/core/phase3/lib/performOperations.ts, packages/e2e-test/steps/hooks.ts, packages/e2e-test/utils/message.ts, packages/e2e-test/utils/world.ts
- [Legacy Bichard retries a PNC update when the PNC returns a lock error.](https://github.com/ministryofjustice/bichard7-next/blob/7f6423adfd7bc73caec4c39ffe7d98038c48e8a8/bichard-api-services/src/main/java/uk/gov/ocjr/mtu/br7/api/services/pnc/impl/PNCASNUpdateFacade.java#L100-L192)
- [It does this a maximum of 3 times and delays the update by 10 seconds.](https://github.com/ministryofjustice/bichard7-next/blob/3d50619ccb8e21b788af24f1ee77712c889ceb15/bichard-api-services/src/main/java/uk/gov/ocjr/mtu/br7/api/services/pnc/impl/PNCASNUpdateFacade.java#L39-L41)
- Add retrying for PNC lock errors in Phase 3.
- Add environment variable for delay so we don't add delay when running comparison tests and unit tests. Simply checking for `NODE_ENV` isn't viable because trigger config checks for …
=> Add retrying for PNC lock errors in Phase 3

packages/e2e-test/steps/hooks.ts, packages/e2e-test/utils/auditLogging.ts, packages/e2e-test/utils/message.ts
This originally returned the external correlation IDs which isn't searchable in the Conductor UI and less helpful when debugging failed E2E tests.
=> Fix correlation IDs output for failed E2E tests

packages/ui/src/components/Header/Header.styles.tsx
=> Update CSS to align correctly

packages/ui/cypress/e2e/case-details/reallocate-case.cy.ts, packages/ui/src/pages/court-cases/[courtCaseId]/reallocate.tsx
Only display user notes table and show more link when user notes exist.
| Before | After |
| ------ | ----- |
| ![image](https://github.com/user-attachments/assets/2e5f43b2-f858-473d-877a-133c91f68593) | ![image](https://github.com/user-attachments/assets/e3ae25bc-f3fd-4cfd-b1eb-745d68eea44c) |
=> Update reallocate page to conditionally show user notes

packages/ui/src/features/CourtCaseDetails/CourtCaseDetailsSummaryBox.styles.tsx, packages/ui/src/features/CourtCaseDetails/CourtCaseDetailsSummaryBox.tsx, packages/ui/src/features/CourtCaseDetails/CourtCaseDetailsSummaryBoxField.styles.tsx, packages/ui/src/features/CourtCaseDetails/CourtCaseDetailsSummaryBoxField.tsx
Remove the need for separate styled components to make court name in the court case summary box span across columns by using [grid-column CSS attribute](https://www.w3schools.com/cssref/pr_grid-column.php) i.e. `grid-column: 1 / span 3;`.
https://github.com/user-attachments/assets/b878070d-8f74-47d3-ace7-5f59307d41f1
=> Refactor styling for court name in court case summary box

packages/ui/src/features/CourtCaseFilters/CourtCaseFilterWrapper.styles.tsx, packages/ui/src/features/CourtCaseFilters/CourtCaseFilterWrapper.tsx
This means a scroll bar will only show when necessary.
https://github.com/user-attachments/assets/17b85f48-2d3a-45ea-aa5e-6ae8e534e536
https://github.com/user-attachments/assets/6ad9d93d-b7ad-438f-a3b3-0a5b7259c23c
=> Fix grey bar caused by overflow on case list page

packages/core/comparison/lib/comparePhase3.ts, packages/core/conductor-tasks/bichard_phase_3/processPhase3.integration.test.ts, packages/core/lib/auditLog/generatePncUpdatedLogAttributes.test.ts, packages/core/lib/auditLog/generatePncUpdatedLogAttributes.ts, packages/core/phase3/phase3.test.ts, packages/core/phase3/phase3.ts, packages/e2e-test/utils/actions.next-ui.ts
The attributes for the audit log event follows [exactly what legacy Bichard does atm](https://github.com/ministryofjustice/bichard7-next/blob/3d50619ccb8e21b788af24f1ee77712c889ceb15/bichard-backend/src/main/java/uk/gov/ocjr/mtu/br7/pnc/update/manager/PNCUpdateProcessor.java#L129-L140). The value of operation code
is questionable but having the same behaviour was prioritised for now.
https://dsdmoj.atlassian.net/browse/BICAWS7-3323
=> Add PNC Update applied successfully audit log event in Phase 3

packages/api/src/routes/v1/cases/case.e2e.test.ts, packages/api/src/services/gateways/dataStoreGateways/postgres.ts, packages/api/src/services/gateways/dataStoreGateways/postgres/cases/lockTrigger.ts, packages/api/src/useCases/cases/lockAndAuditLog.integration.test.ts, packages/api/src/useCases/cases/lockAndAuditLog.ts, packages/api/src/useCases/cases/lockAndFetchCase.e2e.test.ts, packages/api/src/useCases/cases/lockAndFetchCase.integration.test.ts, packages/api/src/useCases/cases/lockTriggers.ts, packages/api/src/useCases/cases/lockTriggers.unit.test.ts
When the API endpoint fetches a case, it locks the triggers to the current user if: the case has triggers, the user has access to handle triggers, and the trigger status is unresolved. These events are also stored in DynamoDB (Audit logging)
Tasks covered:
- Add SQL to lock triggers to current user
- Add useCase to add logic for locking
- Add AuditLogging
=> Lock triggers and add audit logs

packages/ui/src/components/Pagination/Pagination.styles.tsx, packages/ui/src/components/Pagination/Pagination.tsx
Make it so when on a wider screen it's evenly spaced between refresh button and pagination results but smaller screens the pagination elements drop onto its own row.
https://github.com/user-attachments/assets/ec23bae4-24fc-435b-a7d6-8f6e59124fe3
https://github.com/user-attachments/assets/655cffb6-1111-48ad-8cbf-f84773b83f42
=> Update spacing for pagination and refresh button

packages/common/AuditLogApiClient/AuditLogApiClient.test.ts, packages/common/AuditLogApiClient/AuditLogApiClient.ts, packages/common/AuditLogApiClient/createApiConfig.ts, packages/conductor/e2e-test/helpers/getAuditLogs.ts, packages/conductor/e2e-test/incomingMessageHandler.e2e.test.ts, packages/core/conductor-tasks/common/storeAuditLogEvents.integration.test.ts, packages/core/conductor-tasks/common/storeAuditLogEvents.ts, packages/core/conductor-tasks/incomingMessageHandler/createAuditLogRecord.integration.test.ts, packages/core/conductor-tasks/incomingMessageHandler/createAuditLogRecord.ts
- Refactored the AuditLogApiClient to use better naming and to be able to configure the `baseUrl` so we can switch over to `/audit-logs` instead of `/messages`
- Made all parts of the Core Worker use this library
=> Use the API client throughout core and enable the base path to be configured

packages/core/comparison/lib/comparePhase3.ts, packages/core/comparison/lib/isPass.ts, packages/core/phase3/lib/getPncCourtCode.test.ts, packages/core/phase3/lib/getPncCourtCode.ts, packages/core/phase3/lib/performOperations.ts, packages/core/types/PncUpdateDataset.ts
A bit of refactoring to some Phase 3 functions and fix issue with comparison tests where we were returning lots of unnecessary intentional differences for when we don't have the outgoing message and triggers (before 13/11/2024). It meant that we weren't checking for the PNC operation requests for these ones which is still valuable.
https://dsdmoj.atlassian.net/browse/BICAWS7-3333
=> Update Phase 3 functions and comparison tests

package-lock.json, packages/ui/cypress/e2e/case-details/view-case-details/sidebar-tabs.cy.ts, packages/ui/cypress/support/e2e.ts, packages/ui/cypress/support/helpers.ts, packages/ui/package.json, packages/ui/src/features/CourtCaseDetails/Sidebar/Sidebar.tsx
We had an accessibility audit and it reported issues with navigating using a keyboard on the case details page.
It mentioned that using the tab key on the case details page through the court case details tabs to the sidebar, it would focus straight to an element within the current sidebar tab.
This has since been fixed when we removed govuk-react however you weren't able to use the arrow keys to move between the sidebar tabs which this PR fixes.
Add switching between tab panels using arrow keys as defined in https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Roles/tablist_role#keyboard_interactions and shown in [GOV.UK Design System tabs example](https://design-system.service.gov.uk/components/tabs/default/#past-week).
The GOVUK Frontend provides the ability to add …
=> Fix sidebar tabs not being keyboard accessible

packages/e2e-test/utils/actions.next-ui.ts, packages/ui/cypress/e2e/case-details/handle-triggers-and-exceptions/exception-permissions.cy.ts, packages/ui/cypress/e2e/case-details/handle-triggers-and-exceptions/manually-resolve-exceptions.cy.ts, packages/ui/cypress/e2e/case-details/handle-triggers-and-exceptions/redirect-when-resolve-triggers-and-exceptions.cy.ts, packages/ui/cypress/e2e/case-details/handle-triggers-and-exceptions/view-exception-handler-prompt.cy.ts, packages/ui/cypress/e2e/case-details/reallocate-case.cy.ts, packages/ui/cypress/e2e/case-details/view-case-details/view-case-details.cy.ts, packages/ui/cypress/e2e/case-details/view-case-details/view-headers.cy.ts, packages/ui/cypress/e2e/switchingFeedback.cy.ts, packages/ui/cypress/support/helpers.ts, packages/ui/src/components/Buttons/LinkButton.tsx, packages/ui/src/features/CourtCaseDetails/Header.tsx, packages/ui/src/pages/switching-feedback.tsx
When tabbing through elements for link buttons you would have to tab twice for it because we created them by wrapping a button with an anchor link.
This removes the need for the button element and follows the approach of how a [start buttons](https://design-system.service.gov.uk/components/button/#start-buttons) are done.
https://github.com/user-attachments/assets/c61f34fb-3512-4f61-b367-451a2b44f5d4
https://github.com/user-attachments/assets/45ac3f7c-dfca-4aa3-b5ff-6de9b6312214
https://dsdmoj.atlassian.net/browse/BICAWS7-3379
=> Fix double focus on link buttons

packages/ui/src/components/Loading.styles.tsx, packages/ui/src/components/Loading.tsx, packages/ui/src/features/CourtCaseDetails/CourtCaseDetails.tsx, packages/ui/src/pages/court-cases/[courtCaseId]/index.tsx
Some police forces have slow connections, so they interact with the application before all the JS is ready. The users are then sent back to the user welcome page.
This is frustrating for the users.
We know why it's slow: a large unnecessary file is included in a chunk. We are using this as a mitigation so we can fix the root cause, but we don't know how long that will take.
Therefore, we've added a spinner to stop users from interacting with the page until it's completely loaded.
https://github.com/user-attachments/assets/d5914029-35e3-4726-8c8f-5acc5bb5ed64
=> Add spinner for Case Details

buildspec.yml
Currently, deployment is failing as a result of enabling api docker build in buildspec. 
In the terraform, port_mapping and load_balancers' container_port need to be fixed. Once these fixes are merged then we should enable api docker build in buildspec and deployment can be resumed with the new changes.
=> Disable api image build in core buildspec

.gitignore, scripts/analytics/pnc-errors-report/analysePncErrors.ts, scripts/analytics/pnc-errors-report/common.ts, scripts/analytics/pnc-errors-report/extractPncErrors.ts, scripts/analytics/pnc-errors-report/getPncResponseReceivedEvents.ts, scripts/analytics/pnc-errors-report/index.ts
This script:
- retrieves `pnc.response-received` audit log events from DynamoDB for the specified date range (start and end arguments)
- filters for PNC errors
- calculates the number of PNC error messages we get for each PNC operation
- outputs to JSON files
It was based off of the usage report script so has some duplication.
Looking to get this into the repo just in case it proves useful again.
https://dsdmoj.atlassian.net/browse/BICAWS7-3423
=> Add script to analyse errors from PNC

packages/ui/cypress/e2e/case-list/filter-cases/filterCases.cy.ts, packages/ui/src/pages/index.tsx
If you selected multiple case ages only one would appear in the URL. This meant that on refreshes, it would show you the one you selected and not all.
This PR fixes this.
=> Fix not showing all case ages in URL

packages/ui/src/features/CourtCaseList/tags/LockedByTag/LockedByText.styles.tsx, packages/ui/src/features/CourtCaseList/tags/LockedByTag/LockedByText.tsx, packages/ui/src/utils/colours.ts
In particular, fixing the font size and making it more consistent with the locked by button like the text alignment.
Values for padding is the same as locked by button.
Also simplify the styling by removing the `govuk-tag` as we just end up trying to override values.
https://github.com/user-attachments/assets/8aff5342-41ed-49de-9388-a66d430d54be
https://github.com/user-attachments/assets/179c0520-2c93-4b4c-8ad6-77cb99d5924e
https://dsdmoj.atlassian.net/browse/BICAWS7-3407
=> Fix styling for locked by text

.circleci/continue_config.yml
If the MS Edges test fails on the merge queue, the merge will be stopped.
It doesn't need to be required.
=> Only do MS Edge tests on the merge queue

packages/api/goss.yaml, packages/api/goss_wait.yaml, packages/conductor/goss.yaml, packages/conductor/goss_wait.yaml, packages/message-forwarder/goss.yaml, packages/message-forwarder/goss_wait.yaml, packages/ui/goss.yaml, packages/ui/goss_wait.yaml, scripts/build-api-docker.sh, scripts/build-core-worker-docker.sh, scripts/build-message-forwarder-docker.sh, scripts/build-ui-docker.sh
* Add `goss_wait.yaml` to remove the need to use `GOSS_SLEEP=`
* Use `GOSS_FILES_PATHS=` in scripts that used `GOSS_FILE=` to see `goss_wait.yaml`
=> Use goss_wait.yaml in core

packages/ui/src/services/resolveTriggers.ts, packages/ui/test/services/resolveTriggers.integration.test.ts
This PR adds the court case ID to some of our error logs when dealing with Triggers. We were looking into an issue on Friday and it was hard to distinguish what we were looking at.
=> Add courtCaseId to errors for better debuging

packages/ui/cypress/e2e/case-list/filter-cases/filterCases.cy.ts, packages/ui/src/components/Preview.tsx, packages/ui/src/components/PreviewButton.tsx, packages/ui/src/features/CourtCaseDetails/Sidebar/PncDetails/PncCourtCaseAccordion.styles.tsx, packages/ui/src/features/CourtCaseDetails/Sidebar/PncDetails/PncCourtCaseAccordion.tsx, packages/ui/src/features/CourtCaseDetails/Sidebar/Trigger.tsx, packages/ui/src/features/CourtCaseFilters/ExpandingFilters.styles.tsx, packages/ui/src/features/CourtCaseFilters/ExpandingFilters.tsx, packages/ui/src/features/CourtCaseList/CourtCaseListEntry/CaseDetailsRow/CaseDetailsRow.tsx, packages/ui/src/features/CourtCaseList/CourtCaseListEntry/CaseDetailsRow/NotePreviewButton.tsx, packages/ui/src/features/CourtCaseList/CourtCaseListEntry/CaseDetailsRow/NotePreviewRow.tsx
- Case Filter
- Reason
- Court date
- Case resolved date
- Locked state
- Case List
- notes
- Side Panel on Case Details
- **More information** under triggers
- PNC details
=> Toggle buttons are accessible and clearly announce their expanded or collapsed state

packages/conductor/deploy/ConductorGateway.ts, packages/conductor/deploy/EventHandler.ts, packages/conductor/deploy/deploy.ts, packages/e2e-test/utils/actions.next-ui.ts
In #1450, we removed the event handler JSON for handling new comparison messages and in https://github.com/ministryofjustice/bichard7-next-infrastructure/pull/1681 we removed the comparisonQueue SQS.
However by removing the JSON file, this didn't actually remove it from Conductor. We have a `deploy.ts` script which uses the Conductor API that can create and update workflows, tasks, and event handlers but we've never had to delete ones before.
As a result of removing the comparisonQueue the thing that the event handler listening to and not actually removing the event handler properly, Conductor continued to listen and throw an error. This is our current theory for why E2E tests are failing in our deployment pipeline atm.
We expect that we need to update the script to also delete workflows …
=> Remove deleted event handlers from Conductor

packages/conductor/deploy/deploy.ts
Related to #1454.
Deployment pipeline failed on running the script because of the import for `isError`, confusingly it's able to import `EventHandlerDef` in the `ConductorGateway` and runs fine locally and in CI but just fix it, we're avoiding importing.
=> Refactor deploy script for Conductor to not use imported isError

packages/help/site/support/index.md
We no longer use ServiceNow to support users so this PR updates the support page to contact us via our support email instead. Also removed telling users to go to access page and clicking the link as that just takes users to our support email anyway.
=> Update support page in help guidance to remove ServiceNow

packages/ui/src/components/Buttons/LinkButton.styles.tsx, packages/ui/src/components/Buttons/LinkButton.tsx, packages/ui/src/features/CourtCaseDetails/CourtCaseDetailsSummaryBoxField.styles.tsx, packages/ui/src/features/CourtCaseDetails/Header.styles.tsx, packages/ui/src/features/CourtCaseDetails/Sidebar/Trigger.styles.tsx, packages/ui/src/features/CourtCaseDetails/Sidebar/TriggersList.styles.tsx
This PR has following changes for 768 viewport 
- Reduce defendant name fonts size to 19px
- Reduce summary box details font size to 16px
- Reduce all button text size to 16px 
- Reduce side panel font size to 16px 
- Reduce triggers check box size to 30px from 44px.
=> Implement Responsive Layout for 768px Viewport

scripts/get-vpn-config.sh, scripts/import-openvpn-profiles.sh
This PR updates import-vpn-profiles script to:
- Only ask once for aws-vault profile password and mfa
- Import LEDS VPC VPN if LEDS VPN exists in the environment
=> Update import-vpn-profiles script to import leds vpc vpn

packages/ui/cypress/e2e/case-details/lock-cases.cy.ts, packages/ui/cypress/e2e/case-details/view-case-details/view-headers.cy.ts, packages/ui/src/features/CourtCaseDetails/Header.tsx, packages/ui/src/features/CourtCaseDetails/Sidebar/ExceptionsList.tsx, packages/ui/src/features/CourtCaseDetails/Sidebar/TriggersList.tsx
Note: You will see the before image if the user has locked the case and doesn't have a full name. E.g. with test data.
=> Don't show locked by if no exceptions or triggers

packages/ui/src/components/Exception/DefaultException.tsx
The More information links are announced as “More information link” with no further details regarding the purpose of the link. There are multiple links in the section with the same label, and screen reader users would not easily be able to identify the difference between them.
This PR adds a span element within the link that is visually hidden using CSS to detail which code the "more information" relates to.
=> BICAWS7-3392 Link purpose not announced by screen readers

packages/ui/src/components/Radios/RadioButton.tsx, packages/ui/src/components/SearchFilters/CourtDateFilter.tsx
On the Search Panel on the Case List page, the radio button within the Court Date filter contain conditionally revealed inputs. For instance, choosing the ‘Case Received’ radio button reveals a list of checkboxes that can be selected. Visually, it is clear that when users select this the field expands, but this information is not communicated via screen readers. 
This PR adds a visually-hidden <span> element to the label that informs screen reader users of the secondary input.
=> BICAWS7-3390 Secondary inputs make use of invalid ARIA attributes 

packages/ui/src/features/CourtCaseDetails/Header.styles.tsx
The header should be 24px (1.5rem) on all screen sizes.
The content should be 19px (1.1875rem) on larger screen sizes and 16px (1rem) on smaller (> 768px) screen sizes.
=> BICAWS7-3574 - Change case details key information font sizes

packages/ui/src/features/CourtCaseDetails/Tabs/CourtCaseDetailsTabs.styles.tsx, packages/ui/src/features/CourtCaseDetails/Tabs/CourtCaseDetailsTabs.tsx
There was an alignment issue with the tabs on a medium sized screen (between 1000-1200px)
Before:
After:
There are issues with the triggers/exceptions/pnc details box but will sort in a separate PR
=> BICAWS7-3570 - Fix alignment issues on case details screen

packages/ui/src/services/reallocateCourtCase/recalculateTriggers.ts, packages/ui/test/services/reallocateCourtCase/recalculateTriggers.test.ts
This PR fixes an issue with reallocation when `triggerItemIdentity` is `null` and `offenceSequenceNumber` is `undefined`.
Triggers retrieved from the database are converted into the same schema as those generated by the `generateTriggers` function.  
However, `offenceSequenceNumber` in `generateTriggers` can only be a number or `undefined`.
The conversion logic for database trigger entities was not mapping `null` to `undefined`,  
causing trigger matching failures and resulting in triggers being incorrectly deleted.
=> Fix trigger reallocation when triggerItemIdentity is null and offenceSequenceNumber is undefined

packages/ui/src/features/CourtCaseDetails/Sidebar/Sidebar.styles.tsx
Currently the secondary button goes full width on a smaller screen:
This has now been updated so it stays to the right on the compact screensizes:
=> BICAWS7-3631 Secondary button on case details should not go full width on a small screen

packages/ui/src/features/CourtCaseDetails/Header.styles.tsx
Before screens
After screens:
Compact size - 
Regular size -
=> BICAWS7-3633 Fix misalignment of locked status on case details screen

packages/e2e-test/utils/actions.next-ui.ts, packages/ui/cypress/component/Tabs.cy.tsx, packages/ui/cypress/e2e/case-details/handle-triggers-and-exceptions/edit-fields-with-exceptions/exception-resolved-message.cy.ts, packages/ui/cypress/e2e/case-details/handle-triggers-and-exceptions/triggers/locked-icon.cy.ts, packages/ui/cypress/e2e/case-details/handle-triggers-and-exceptions/triggers/triggers-and-exceptions-tabs.cy.ts, packages/ui/cypress/e2e/case-details/offence-matching/HO100203.cy.ts, packages/ui/cypress/e2e/case-details/reallocate-case.cy.ts, packages/ui/cypress/e2e/case-details/view-case-details/view-case-details.cy.ts, packages/ui/cypress/e2e/case-details/view-case-details/view-pnc-details.cy.ts, packages/ui/src/components/Tabs/TabHeaders.styles.tsx, packages/ui/src/components/Tabs/TabHeaders.tsx, packages/ui/src/components/Tabs/TabPanel.tsx, packages/ui/src/components/Tabs/Tabs.styles.tsx, packages/ui/src/components/Tabs/Tabs.tsx, packages/ui/src/components/Tabs/index.tsx, packages/ui/src/features/CourtCaseDetails/Sidebar/Sidebar.styles.tsx, packages/ui/src/features/CourtCaseDetails/Sidebar/Sidebar.tsx, packages/ui/src/hooks/useRefreshCsrfToken.ts
Currently, the tab components are just part of the sidebar component. This PR:
* Splits them off into new components with self-contained logic
* Adds cypress component tests
=> BICAWS7-3647 - Split tabs into their own components

packages/common/types/ApiCaseQuery.ts
Add to the search query in the API and UI for the ability to show cases with date differences (court date and message received timestamp).
=> Add filter to ApiCaseQuerySchema for compare dates

packages/api/src/server/openapi/setupSwagger.ts
Missed change during the Zod upgrade.
Schemas were not showing in the Swagger JSON/UI.
=> Fix Swagger docs

packages/api/src/routes/v1/audit-logs/searchAuditLogs.e2e.test.ts, packages/api/src/types/AuditLog.ts, packages/api/src/types/AuditLogEvent.ts, packages/common/schemas/unvalidatedHearingOutcomeJson.ts, scripts/generate-schema-doc.sh
- Remove Ajv warning
- Fix the generated schema doc again
- Other small fixes
- Had to create a new Zod schema for JSON output. This is used for the Arch Documentation. 
- See this file: `scripts/generate-schema-doc.sh`
- With JSON schema `z.coerce.date()` causing an error to be thrown
- So I've had to create a JSON specific file with `z.string().meta({ format: "date" })` so that it doesn't throw an error
=> Tidy up schemas

scripts/generate-schema-doc.sh
We had a wildcard in a bash script that selected all the top-level files into a TypeScript snippet.
=> Remove wildcard

packages/e2e-test/e2eTestBuildspec.yml
In the current e2e-test CodeBuild jobs, only the common package is built as a dependency of the e2e-test package. Since we now also reference the core package, this PR updates the buildspec file to run the `build:e2e-test` npm script, ensuring that all required dependency packages for e2e-test are built.
=> Update e2e test codebuilds to build core package

packages/api/src/services/db/cases/fetchCaseAges.e2e.test.ts
I've adjusted this test so the next time it fails we will have some more information as to what the full `caseMetadata` looks like to hopefully begin to understand why this test is flaky in CI.
=> BICAWS7-3675 - Adjust flaky API e2e test

packages/conductor/e2e-test/resubmit.e2e.test.ts, packages/conductor/tasks/check_db.json, packages/conductor/tasks/process_resubmit.json, packages/conductor/workflows/resubmit.json, packages/core/conductor-tasks/resubmit/check_db.integration.test.ts, packages/core/conductor-tasks/resubmit/check_db.ts, packages/core/conductor-tasks/resubmit/process_resubmit.integration.test.ts, packages/core/conductor-tasks/resubmit/process_resubmit.ts
Loading the case from the DB between `check_db` and `process_resubmit` task, a user could unlock the case.
That caused the Audit Log Events without a username, which is not allowed.
This PR fixes this by taking the username at the `check_db` task and storing (S3) the username for later use.
=> Fix race condition in resubmit via Conductor

packages/api/src/routes/v1/cases/resubmit.ts, packages/core/conductor-tasks/resubmit/check_db.ts, packages/core/conductor-tasks/resubmit/process_resubmit.ts
Relax the Zod parsing as we have some `message_id` that match UUIDs
=> Handle invalid UUID
