src/lib/convertASNToLongFormat.test.ts
src/lib/convertASNToLongFormat.ts
src/use-cases/enrichHearingOutcome/enrichFunctions/enrichDefendant.test.ts
src/use-cases/enrichHearingOutcome/enrichFunctions/enrichDefendant.ts
src/use-cases/enrichHearingOutcome/enrichFunctions/index.ts
src/use-cases/enrichHearingOutcome/index.ts
test-data/input-message.xml.njk
tests/helpers/generateMessage.ts
tests/helpers/generateMockAho.ts

Also adds a generateMockAho function for use elsewhere

Implement the enrichDefendant phase of enrichment

---

package-lock.json
package.json
src/lib/generateLegacyAhoXml.test.ts

The generated result has a dependency on the current date

Fix generateLegacyAhoXml unit test

---

src/types/PncGateway.ts
src/use-cases/enrichHearingOutcome/enrichFunctions/enrichWithPncQuery.ts
tests/comparison.test.ts
tests/helpers/MockPncGateway.ts
tests/helpers/generateMockPncQueryResultFromAho.ts
tests/helpers/getPncQueryTimeFromAho.ts

so we can inject it in the tests to make the XML match

Extract the PNC query time from the gateway

---

package-lock.json
package.json
src/use-cases/dataLookup/lookupPsaCodeByCrownCourtName.ts

Automated standing data update generated by the [Release](https://github.com/ministryofjustice/bichard7-next-data/actions/workflows/release.yml) workflow.

Update standing data

---

src/types/IncomingMessage.ts
src/use-cases/transformSpiToAho/PopulateOffenceResults.ts
src/use-cases/transformSpiToAho/lookupAmountTypeByCjsCode.ts
src/use-cases/transformSpiToAho/populateCase.ts
src/use-cases/transformSpiToAho/populateDefendant.ts

Check the individual commits for details

Fix some more inconsistencies in our XML generation

---

src/lib/generateLegacyAhoXml.ts

Before: 170 failed
After: 166 failed

Fix 4 more tests by removing whitespace after <br7:BailCondition>s

---

src/lib/offenceMatcher/offenceMatcher.ts
src/use-cases/enrichHearingOutcome/enrichFunctions/enrichCourtCases/addNullOffenceReasonSequence.ts
src/use-cases/enrichHearingOutcome/enrichFunctions/enrichCourtCases/enrichOffencesFromCourtCasesAndMatcherOutcome.ts
src/use-cases/enrichHearingOutcome/enrichFunctions/enrichCourtCases/enrichOffencesFromMatcherOutcome.ts

Also make sure we are able to output an error if the element is missing for the OffenceReasonSequence

Fix case matching issue in comparison tests

---

src/lib/generateLegacyAhoXml.ts
src/lib/parseAhoXml.ts
src/types/AnnotatedHearingOutcome.ts
src/use-cases/enrichHearingOutcome/enrichFunctions/enrichCourtCases/addNullCourtCaseReferenceNumber.ts
src/use-cases/enrichHearingOutcome/enrichFunctions/enrichCourtCases/enrichOffencesFromCourtCasesAndMatcherOutcome.ts
src/use-cases/transformSpiToAho/PopulateOffences.ts
tests/comparison.test.ts

See the individual commits for details

Improve comparisons

---

.circleci/config.yml
src/lib/excludedTriggerConfig.ts
src/triggers/TRPR0027.ts

All comparison tests are now passing! 🎉

Fix the issue with trigger 4 and add the comparison tests to CI

---

README.md
package-lock.json
package.json
src/comparison/DynamoGateway/DynamoGateway.ts
src/comparison/cli.ts
src/comparison/cli/getArgs.ts
src/comparison/cli/main.ts
src/comparison/cli/printOutput.ts
src/comparison/cli/processFile.ts
src/comparison/cli/processRange.ts
src/comparison/compare.ts
src/comparison/getFileFromS3.ts

```
Options
-f, --file string     Specify either the local file path or an S3 URL                               
-s, --start string    Specify the start timestamp in ISO8601 format                                 
-e, --end string      Specify the end timestamp in ISO8601 format                                   
-p, --filter string   Filter based on the last result. Specify either 'failure', 'success', 'both'. 
Default is 'failure'                                                          
-h, --help            Prints this usage guide   
```

Improve cli comparison tool

---

.npmrc
buildspec.yml

* codebuild job was failing to build as the `NPM_TOKEN` var could not be found

chore: 🤖 remove npmrc

---

src/comparison/cli/printResult.ts
src/enrichAho/enrichFunctions/enrichCourtCases/enrichOffencesFromMatcherOutcome.ts
src/enrichAho/enrichFunctions/enrichCourtCases/index.ts
src/enrichAho/enrichFunctions/enrichCourtCases/matchMultipleCases.ts
src/enrichAho/enrichFunctions/enrichOffences/parseAsn.test.ts
src/enrichAho/enrichFunctions/enrichOffences/parseAsn.ts
src/lib/offence/createCriminalProsecutionRef.ts
src/serialise/ahoXml/generate.ts
src/types/ParsedAsn.ts
tests/helpers/mockRecordInPnc.ts

See the individual commits for details. This now brings the pass rate up to 100% for the week of the 4th July

Fix 7th july

---

src/comparison/cli/main.ts
src/comparison/cli/processRange.ts
src/comparison/getDateFromComparisonFilePath.ts
src/comparison/logInDynamoDb.integration.test.ts
src/comparison/logInDynamoDb.ts

Update compare lambda to read initial run at from the S3 path.

Read initial run at from S3 path

---

package.json

Forgot to bump the package! 😵‍💫

Bump package version to v1.1.1

---

.npmignore
package.json

- Added some missing files to `.npmignore` to help keep package size down
- Bumped package to `v1.1.2` and slightly changed the description

Minor improvements to core packaging

---

package.json
src/lib/dates.test.ts
src/lib/dates.ts
src/parse/transformSpiToAho/getRemandDetailsFromResultText.ts
src/parse/transformSpiToAho/removeSeconds.ts
src/serialise/ahoXml/generate.ts
tests/helpers/mockRecordInPnc.ts

Ran into some issues with the parsing and serialisation of dates because of UTC. Hopefully this will make it more consistent. I've removed the external library we were using because it was handling a particular edge case incorrectly.

Re-work the timestamp handling so that it is more consistent

---

src/lib/organisationUnit/populateOrganisationUnitFields.ts

but the Java code we ported does

JS doesn't throw an error if the substring index is out of bounds

---

src/enrichAho/enrichFunctions/enrichCourtCases/enrichOffencesFromMatcherOutcome.ts
src/enrichAho/enrichFunctions/enrichForceOwner.ts
src/parse/transformSpiToAho/populateDefendant.ts
src/schemas/annotatedHearingOutcome.ts

Comparison fixes

---

src/enrichAho/enrichFunctions/enrichWithPncQuery.ts
src/index.test.ts
src/index.ts
src/lib/auditLog/getAuditLogEvent.ts
src/lib/auditLog/getHearingOutcomePassedToErrorListLog.ts
src/lib/auditLog/getIncomingMessageLog.ts

Add the following audit logs to core:
- Hearing Outcome ignored as it contains no offences
- Hearing Outcome passed to Error List

BICAWS-2238 Add audit logs to core Part2

---

package.json
src/types/Phase.ts
src/types/ResolutionStatus.ts

Small PR to add two types to core:
- Phase
- ResolutionStatus 
We will be using these in the new UI to allow user to apply updates to a HO

Exporting functions and types for UI

---

package.json

Release package with AnnotatedPNCUpdateDataset parser

Bump package version to 1.1.6

---

src/lib/encoding.ts

This caused comparison tests to fail

Revert encoding change

---

src/enrichAho/enrichFunctions/enrichWithPncQuery.test.ts
src/enrichAho/enrichFunctions/enrichWithPncQuery.ts
src/index.test.ts
src/index.ts
src/lib/CoreAuditLogger.test.ts
src/lib/CoreAuditLogger.ts
src/lib/auditLog/getAuditLogEvent.ts
src/lib/auditLog/getHearingOutcomePassedToErrorListLog.ts
src/lib/auditLog/getIncomingMessageLog.ts
src/steps/phase1/index.ts
src/steps/phase1/processPhase1.integration.test.ts
src/steps/phase1/processPhase1.ts
src/steps/phase1/storeAuditLogEvents.integration.test.ts
src/steps/phase1/storeAuditLogEvents.ts
src/types/AuditLogEvent.ts
src/types/Phase1Result.ts
tests/helpers/processMessage.ts

Relatively simple step to write the audit logs we output to the Audit Log API

Phase1 audit logs

---

airflow/dags/compare_single_dag.py

This PR update compare single DAG to get compare single lambda function name from an environment variable.

Update compare single lambda to get function name from env vars

---

buildspec.yml

chore: 🤖 set node memory size

---

buildspec.yml
environment/boot.sh
environment/docker-compose-worker.yml
environment/docker-compose.yml

And a couple of other minor tweaks

Remove elasticsearch

---

scripts/skip-test.ts
scripts/summariseRecord.ts
src/comparison/cli/fetchFile.ts
src/comparison/cli/printPncMatchingResult.ts
src/comparison/cli/printResult.ts
src/comparison/cli/processRange.ts
src/comparison/types/ComparisonLog.ts

Also add some small improvements to our utilities scripts (skipping and summarising)

Skip intentional differences in dynamo

---

scripts/summariseRecord.ts
src/comparison/lib/isIntentionalMatchingDifference/invalidManualSequenceNumber.ts
src/comparison/lib/isIntentionalMatchingDifference/matchingToFinalOffences.ts
src/comparison/types/MatchingComparisonOutput.ts
src/enrichAho/enrichFunctions/matchOffencesToPnc/matchOffencesToPnc.test.ts
tests/helpers/summariseMatching.ts

July week1 fixes - part 1

---

src/enrichAho/enrichFunctions/matchOffencesToPnc/OffenceMatcher.ts
src/enrichAho/enrichFunctions/matchOffencesToPnc/matchOffencesToPnc.test.ts

Added full case matching to matching algorithm

Full case matching

---

.github/workflows/publish-architecture.yml

Dependency is broken. We need to wait for the `v0.6.0` version.
https://github.com/abiosoft/colima/issues/778#issuecomment-1676817841

Fix generating docs

---

.circleci/config.yml
packages/message-forwarder/Dockerfile

We were not building the message forwarder in the dockerfile

Added npm run build

---

environment/postgres/liquibase/seeds/base/007_update_feature_flag_with_exceptions_enabled.sql

This PR enables test users and dev's to have the `exceptionsEnable` feature set to true when the seed script runs

Created new seed script for exceptionsEnabled feature flag

---

scripts/analytics/new-ui-usage-report.ts

PR to add a script to extract audit log events and generates reports for the new UI.

Add new UI report script

---

packages/core/phase1/dataLookup/lookupOrganisationUnitByCode.ts
packages/core/phase1/enrichAho/enrichFunctions/enrichWithPncQuery.test.ts
packages/core/phase1/enrichAho/enrichFunctions/enrichWithPncQuery.ts
packages/core/phase1/phase1.ts

- OU code lookups
- Not generating exceptions for ignored cases

Fix some more differences from legacy

---

packages/conductor/workflows/incoming-message-handler.json

Fixes an issue found in conductor when running e2e tests

Added timestamp field to auditLogEvents

---

scripts/dev-sgs.sh

This PR updates the `npm run dev-sgs` script to include the UAT environment

Updated dev-sgs.sh to include uat environment

---

packages/api/src/services/getDataSource.ts
scripts/analytics/usage-report/WorkbookGenerator.ts
scripts/analytics/usage-report/findUsersWithAccessToNewUi.ts
scripts/analytics/usage-report/index.ts

This updates the usage report to produce the following data and adds them to a new sheet/tab in the spreadsheet :
- XX People have the new UI turned on
- XX People resolved a trigger on the new UI
- XX People resolved an exception on the new UI
- Of XX people who have the UI turned on, XX.XX% of their triggers were resolved in the new UI
- Of XX people who have the UI turned on, XX.XX% of their exceptions were resolved in the new UI

Update usage report script to add monthly stats tab

---

packages/core/phase2/pncUpdateDataset/createTriggerIfNecessary.ts
packages/core/phase2/pncUpdateDataset/getGenericTriggerCaseOrOffenceLevelIndicator.ts
packages/core/phase2/pncUpdateDataset/identifyPostUpdateTriggers.ts
packages/core/phase2/pncUpdateDataset/isAppealAllowed.ts

Adds further skeleton logic to be implemented in separate tickets

BICAWS7-2853 identifyPostUpdateTriggers

---

packages/core/phase2/pncUpdateDataset/identifyPostUpdateTriggers.ts

Implements missing logic from Bicaws7 2855

Bicaws7 2855

---

packages/core/phase2/pncUpdateDataset/identifyPostUpdateTriggers.ts

Completes implementation of identifyPostUpdateTriggers
Removes todo which doesn't need to be implemented here as it is part of the xml serialisation

Bicaws7 2858

---

packages/core/comparison/lib/comparePhase2.ts

Compare triggers generated in core to comparison data triggers in phase2 comparison testing

Compare triggers

---

packages/conductor/src/worker.ts
packages/conductor/tasks/lock_s3_file.json
packages/core/conductor-tasks/common/lockS3File.integration.test.ts
packages/core/conductor-tasks/common/lockS3File.ts

Also - rename a variable for consistency

Add the lock task to Conductor

---

package-lock.json
packages/conductor/Dockerfile
packages/core/package.json

I'd accidentally reverted the change in the previous PR to use a multistage build so it didn't actually fix the pipeline

Actually use a multistage build for core worker

---

scripts/analytics/legacy-ui-usage/.example.env
scripts/analytics/legacy-ui-usage/Pipfile
scripts/analytics/legacy-ui-usage/Pipfile.lock
scripts/analytics/legacy-ui-usage/README.md
scripts/analytics/legacy-ui-usage/allocatedCases.py
scripts/analytics/legacy-ui-usage/fetchAuthProxyLogs.py
scripts/analytics/legacy-ui-usage/fetchHttpUsers.py
scripts/analytics/legacy-ui-usage/fetchLoginLogs.py
scripts/analytics/legacy-ui-usage/fetchLogs.py
scripts/analytics/legacy-ui-usage/filters.py
scripts/analytics/legacy-ui-usage/reportRunStats.py
scripts/analytics/legacy-ui-usage/search.py

We have some scripts in the legacy application that were used to get some usage data to support our work prioritisation and design decisions. We may need to re-run these in the future so it would be better to have a single place for such scripts in the core repo.
- Move scripts from legacy application
- Add script to get usage data on when users using reports tab

Migrate analytics scripts from legacy application to core

---

package.json
packages/core/phase2/parse/parseAnnotatedPNCUpdateDatasetXml/__snapshots__/parseAnnotatedPNCUpdateDatasetXml.test.ts.snap
packages/core/phase2/parse/parseAnnotatedPNCUpdateDatasetXml/parseAnnotatedPNCUpdateDatasetXml.ts
packages/core/phase2/parse/parsePncUpdateDataSetXml/parsePncUpdateDataSetXml.ts
packages/core/phase2/types/PncUpdateDatasetXml.ts

This PR:
- fixes an issue with parsing Annotated PNC Update Dataset XML
- updates package version to 2.0.6

Fix annotated PNC update dataset parser

---

.github/workflows/release.yml

This PR fixes the issue with exporting output variables from steps in the Release github action.

Fix release github action

---

packages/core/phase1/triggers/TRPS0002.ts
packages/core/phase1/triggers/TRPS0003.ts
packages/core/phase1/triggers/TRPS0008.test.ts
packages/core/phase1/triggers/TRPS0008.ts

- Refactored TRPS0002 and TRPS0003 to use the reduce function
- Updated logic for TRPS0008 to return multiple triggers

Refactor trps0002 trps0003  trps0008

---

packages/core/phase1/triggers/TRPS0013.test.ts

Improved test to cover the case when an offence is recordable and has a number of offence TICs that it should return trigger TRPS0013 and the court offence sequence number.

Refactor of TRPS0013 test to improve coverage.

---

packages/core/phase1/triggers/TRPR0003.test.ts

Add unit tests for TRPR0003 trigger

TRPR0003 unit tests

---

packages/core/phase1/triggers/TRPR0004.test.ts

Here are the scenarios covered:
Result Code | Offence Code | Verdict | Result Text | Expected Trigger | Done?
-- | -- | -- | -- | -- | --
In List | In List | Guilty | Sexual offence | Yes | Yes
In List | In List | Guilty | Non-sexual offence | Yes | Yes
In List | In List | Not Guilty | Sexual offence | Yes | Yes
In List | In List | Not Guilty | Non-sexual offence | Yes | Yes
In List | Not In List | Guilty | Sexual offence | Yes | Yes
In List | Not In List | Guilty | Non-sexual offence | Yes | Yes
In List | Not In List | Not Guilty | Sexual offence | Yes | Yes
In List | Not In List | Not Guilty | Non-sexual offence | Yes | Yes
Not In List | In List | Guilty | Sexual offence | Yes | Yes
Not In List | In List | Guilty | Non-sexual offence | Yes | Yes
Not In List | In List | Not Guilty | …

Unit tests for TRPR0004

---

packages/core/scripts/testServer.ts

Now that we've rewritten Phase 2, we want to enable characterisation tests for it.
In https://github.com/ministryofjustice/bichard7-next-tests/pull/573, we added a `phase` parameter for processing messages in characterisation tests.
- Update test server for characterisation tests to use `phase` to determine whether to return a Phase 1 or Phase 2 result.
- Refactor to use `parseIncomingMessage` for parsing input message.
https://dsdmoj.atlassian.net/browse/BICAWS7-3017

Update test server for characterisation tests to handle phase

---

.circleci/continue_config.yml

Added new CI jobs to run e2e tests against Phase 2 Core.

Phase2 core CI jobs

---

packages/message-forwarder/src/forwardMessage/forwardMessage.ts

We're looking to set up a message forwarder for Phase 2 resubmissions, however atm it's hardcoded to start a Phase 1 workflow.
- Update message forwarder to take in a Conductor workflow name via an environment variable called `CONDUCTOR_WORKFLOW`.
- By default, this is set to `bichard_phase_1`.
- We do a check for valid workflows like destination type.
https://dsdmoj.atlassian.net/browse/BICAWS7-2994

Update message forwarder to take in Conductor workflow name

---

.circleci/continue_config.yml
.github/workflows/publish-architecture.yml
scripts/build-ui-docker.sh
scripts/generate-schema-doc.sh

- CircleCI 
- Don't run if there's no change
- GitHub Action 
- Just build core in the schema generation
- Fix the schema being generated
- AWS pipeline 
- Add missing Goss path

Fix pipelines

---

.circleci/config.yml
.circleci/continue_config.yml

Add e2e tests variable to trigger UI cucumber tests

Trigger e2e tests for UI if e2e tests have changed

---

packages/core/lib/exceptions/addExceptionsToAho.test.ts
packages/core/lib/exceptions/addExceptionsToAho.ts
packages/core/phase1/phase1.ts
packages/core/phase2/phase2.ts

https://dsdmoj.atlassian.net/browse/BICAWS7-2975

Update addExceptionsToAho to handle multiple exceptions instead

---

README.md
packages/api/README.md
packages/common/README.md
packages/conductor/README.md
packages/e2e-test/README.md
packages/uat-data/README.md
packages/ui/Makefile
packages/ui/README.md

- Updated README in
- UI
- e2e tests
- Top level core
- API
- Added README in
- Common
- Made the UI Makefile work again

Update the readme in core for the UI and update the UI readme

---

.circleci/continue_config.yml
.circleci/scripts/ui-scripts/run-component-tests.sh
packages/e2e-test/scripts/run_test_chunk.sh

Fix storing the results of tests for:
- Cypress component tests
- Cypress e2e tests
- Cucumber e2e tests

Record tests in CircleCI

---

packages/e2e-test/scripts/run_test_chunk.sh

Missed if the test run passes we still need to fail the step

Fix not erroring if cucumber errors

---

packages/ui/cypress.config.ts
packages/ui/cypress/e2e/case-list/notePreview.cy.ts
packages/ui/src/features/CourtCaseList/CourtCaseListEntry/CaseDetailsRow/NotePreviewButton.tsx
packages/ui/test/utils/insertCourtCases.ts

  Note preview for cases in the case list should include the note username

---

.vscode/extensions.json
.vscode/settings.json

We want to keep consistency with the code we create. 
I've added some sensible settings and recommended extensions for VS Code.
These are opinionated settings and extensions.

Add defaults to workspace settings

---

.circleci/scripts/run-infrastructure.sh

See https://app.circleci.com/pipelines/github/ministryofjustice/bichard7-next-core/6924/workflows/6e6e5d7d-c049-4c26-8d55-dbd111e03904/jobs/65043
Kill the docker container and try again

Sometimes conductor errors

---

packages/core/comparison/lib/comparePhase3.ts
packages/core/lib/triggers/TRPS0002.ts
packages/core/lib/triggers/TRPS0003.ts
packages/core/lib/triggers/TRPS0004.test.ts
packages/core/lib/triggers/TRPS0004.ts
packages/core/lib/triggers/TRPS0008.ts
packages/core/lib/triggers/TRPS0010.ts
packages/core/lib/triggers/TRPS0011.ts
packages/core/lib/triggers/TRPS0013.ts
packages/core/phase3/phase3.ts

This just involved using the same generator we used for phase 2 and making the phase 2 triggers also apply to phase 3.
In the process I found a bug in TRPS0004. I checked a full week of records and none were raised in phase 2 which I suspect is why the bug wasn't found.

Incorporate triggers into phase 3

---

packages/ui/src/features/CourtCaseFilters/AppliedFilters.tsx
packages/ui/src/features/CourtCaseFilters/CourtCaseFilterWrapper.styles.tsx
packages/ui/src/features/CourtCaseFilters/CourtCaseFilterWrapper.tsx

Fix layout of applied filters

---

packages/core/phase3/lib/hearingDetails/createAdjudicationFromOffence.ts
packages/core/phase3/lib/hearingDetails/createArrestHearingFromOffence.ts
packages/core/phase3/lib/hearingDetails/createCourtHearingFromOffence.ts
packages/core/phase3/lib/hearingDetails/createDisposalsFromOffence.ts
packages/core/phase3/lib/hearingDetails/generateArrestHearingsAdjudicationsAndDisposals.ts
packages/core/phase3/lib/hearingDetails/generateHearingsAdjudicationsAndDisposals.ts
packages/core/phase3/lib/hearingDetails/generateHearingsAndDisposals.ts
packages/core/phase3/lib/pncUpdateRequestGenerators/normalDisposalGenerator.ts
packages/core/phase3/types/DisposalUpdatedPncUpdateRequest.ts
packages/core/phase3/types/HearingDetails.ts
packages/core/phase3/types/NormalDisposalPncUpdateRequest.ts
packages/core/phase3/types/PenaltyHearingPncUpdateRequest.ts
packages/core/phase3/types/SentenceDeferredPncUpdateRequest.ts

The types like `Disposal` and `Adjudication` aren’t clearly distinguishable from `PncDisposal` and `PncAdjudication`.
https://dsdmoj.atlassian.net/browse/BICAWS7-3292

Rename types for hearing details in Phase 3

---

environment/docker-compose.yml
package.json
packages/conductor/e2e-test/bichardPhase1.e2e.test.ts
packages/conductor/e2e-test/bichardPhase2.e2e.test.ts
packages/conductor/e2e-test/bichardPhase3.e2e.test.ts
packages/conductor/e2e-test/helpers/getAuditLogs.ts
packages/conductor/e2e-test/helpers/getFixture.ts

https://dsdmoj.atlassian.net/browse/BICAWS7-3278

Enable skipped E2E tests for Conductor workflows

---

packages/core/phase3/lib/pncUpdateRequestGenerators/normalDisposalGenerator/normalDisposalGenerator.ts
packages/core/phase3/lib/pncUpdateRequestGenerators/normalDisposalGenerator/preProcessPreTrialIssuesUniqueReferenceNumber.test.ts
packages/core/phase3/lib/pncUpdateRequestGenerators/normalDisposalGenerator/preProcessPreTrialIssuesUniqueReferenceNumber.ts

https://dsdmoj.atlassian.net/browse/BICAWS7-3307

Refactor getting PTIURN in normal disposal generator

---

packages/api/src/services/parseHearingOutcome.ts
packages/api/src/services/parseHearingOutcome.unit.test.ts
packages/api/src/tests/helpers/ahoHelper.ts
packages/api/src/tests/helpers/fakeLogger.ts
packages/api/src/useCases/dto/convertCaseDBToDTO.ts
packages/api/src/useCases/dto/fetchFullCaseDTO.ts
packages/api/src/useCases/dto/fetchFullCaseDTO.unit.test.ts

- Add a FakeLogger class
- Remove optional param

API FakeLogger for tests

---

packages/ui/next-env.d.ts

Update next-env file generated by Nextjs

Update next-env file

---

package-lock.json
packages/ui/package.json
packages/ui/src/components/ActionLink.tsx
packages/ui/src/components/Pagination/CasesPerPage.styles.tsx
packages/ui/src/components/Pagination/CasesPerPage.tsx
packages/ui/src/features/CourtCaseList/tags/LockedByTag/LockedByButton.styles.tsx
packages/ui/src/features/CourtCaseList/tags/LockedByTag/LockedByButton.tsx

| Before | After |
| ------ | ----- |
| ![image](https://github.com/user-attachments/assets/dbacfa43-11f7-4162-ba79-cd7cbfd4e546)  | ![image](https://github.com/user-attachments/assets/b78810b8-bdc4-4194-9ae9-b222ae552cd9) |
| ![image](https://github.com/user-attachments/assets/70762913-da5f-412c-9c27-7d29adaae4b4) | ![image](https://github.com/user-attachments/assets/afe683b7-a1ab-4eb0-b664-d9125ac9b877) |
| ![image](https://github.com/user-attachments/assets/7a88cd88-6bce-4e94-a443-5da3567c12be) | ![image](https://github.com/user-attachments/assets/fe41ff1c-540a-4db7-bba6-fb20d3973e45) |

Ensure GDS font is used in UI

---

packages/e2e-test/utils/actions.next-ui.ts
packages/ui/src/components/ResolutionStatusTag.styles.tsx
packages/ui/src/components/ResolutionStatusTag.tsx

Fix styling of manually resolved

---

packages/ui/src/components/SearchFilters/TriggerGroups.styles.tsx
packages/ui/src/features/CourtCaseDetails/CourtCaseDetails.styles.tsx

https://github.com/user-attachments/assets/7da173ec-3e79-47d0-bb65-0e17a4cc8396

Fix random grey bars caused by overflow in UI

---

packages/common/utils/userPermissions.test.ts
packages/ui/src/utils/userPermissions.test.ts

We were importing the User from the `ui` package, which caused the `common` package's `tsconfig` to error. 
We are now testing the local users in the `common` and `ui` packages

Fix common tsconfig

---

.github/workflows/format-code.yml
packages/core/comparison/lib/comparePhase3.ts
packages/core/lib/triggers/TRPR0003.ts
packages/core/phase3/lib/performOperations.test.ts
packages/core/phase3/lib/performOperations.ts
packages/core/phase3/lib/updatePnc.test.ts
packages/core/phase3/lib/updatePnc.ts
packages/core/scripts/files-from-comparison.js

https://dsdmoj.atlassian.net/browse/BICAWS7-3332

Extract updatePnc function into its own file

---

packages/ui/src/services/api/ApiClient.ts
packages/ui/src/services/api/BichardApiV1.test.ts
packages/ui/src/services/api/BichardApiV1.ts
packages/ui/src/services/api/interfaces/BichardApiGateway.ts
packages/ui/src/services/api/interfaces/HttpClient.ts
packages/ui/test/helpers/api/fakeApiClient.ts

- Use the ApiClient
- Add first endpoint call

Add gateway to UI for API

---

packages/ui/src/config.ts

* Contains a USE_API env variable to control the whole global use of API. 
* Contains a USE_API_CASE_ENDPOINT env variable to control an endpoint

Use env variables to enable using the API

---

packages/ui/cypress/component/CaseListFilter/TriggerGroups.cy.tsx
packages/ui/cypress/e2e/case-list/filter-cases/triggersExcludedAll.cy.ts
packages/ui/cypress/e2e/case-list/filter-cases/triggersJustWarrantsEnabled.cy.ts
packages/ui/cypress/fixtures/users.ts
packages/ui/src/components/SearchFilters/TriggerGroups.tsx

Fix bug 'selected' checkboxes in trigger groups

---

packages/api/src/routes/v1/cases/case.ts
packages/api/src/server/schemas/errorReasons.ts
packages/api/src/services/gateways/dataStoreGateways/postgres/cases/fetchCase.ts
packages/api/src/services/gateways/dataStoreGateways/postgres/cases/selectMessageId.ts
packages/api/src/types/errors/UnprocessableEntityError.ts

- Create/Handle 404 errors
- Create/Handle 422 errors
- Create/Handle 403 errors

Provide more error codes from API /cases/:caseId endpoint

---

packages/ui/src/components/Layout.styles.tsx

Add whitespace so the case list page looks good

---

packages/core/conductor-tasks/bichard_phase_2/sendToPhase3.integration.test.ts
packages/core/conductor-tasks/bichard_phase_2/sendToPhase3.ts

This was creating files with "{SOME_UUID}-phase2-phase3.json".

Fix s3TaskDataPath for Core Phase 3 files

---

packages/ui/src/components/Buttons/LinkButton.tsx
packages/ui/src/features/CourtCaseDetails/Header.tsx
packages/ui/src/features/CourtCaseDetails/Sidebar/ExceptionsList.tsx
packages/ui/src/features/CourtCaseList/tags/LockedByTag/LockedByButton.tsx
packages/ui/src/pages/switching-feedback.tsx

* Add more buttons that need to be disabled e.g. "Leave and unlock"
* Add the same behaviour to LinkButton so the UI is consistent
* Support `onClick` from parent `onClick` handlers

More buttons need disabling

---

packages/ui/src/components/FilterChip.styles.tsx
packages/ui/src/components/FilterTag/FilterTag.styles.tsx

* Make the font colour black
* Make the cross black

Fix white on yellow text

---

packages/help/site/assets/moj-frontend.scss
packages/ui/src/pages/_document.tsx

https://dsdmoj.atlassian.net/browse/BICAWS7-3380

Add skip to main content link

---

packages/ui/cypress/e2e/infoBanner.cy.ts
packages/ui/src/components/InfoBanner.tsx

Fix logic for banner expiry. 
The test checking banner expiring after 5 days wasn't passing for right reasons.

Fix info-banner

---

packages/ui/cypress/e2e/case-list/filter-cases/filterByResolvedDate.cy.ts
packages/ui/src/features/CourtCaseFilters/reducers/handleAddingFilters.ts
packages/ui/src/services/listCourtCases.ts

When using the Case Resolved date range, automatically set the case state as Resolved.

Add Resolved case state to selected when selecting case resolved date range

---

packages/e2e-test/utils/actions.next-ui.ts
packages/ui/src/components/Exception/DefaultException.tsx
packages/ui/src/features/CourtCaseDetails/CourtCaseDetails.tsx
packages/ui/src/features/CourtCaseDetails/Sidebar/TriggersList.tsx
packages/ui/src/features/CourtCaseDetails/Tabs/CourtCaseDetailsSingleTab.tsx
packages/ui/src/features/CourtCaseDetails/Tabs/Panels/Offences/Offence/BackToAllOffencesLink.tsx
packages/ui/src/features/CourtCaseDetails/Tabs/Panels/Offences/OffencesList/OffencesList.styles.tsx
packages/ui/src/features/CourtCaseDetails/Tabs/Panels/Offences/OffencesList/OffencesList.tsx
packages/ui/src/features/CourtCaseDetails/Tabs/Panels/Offences/OffencesList/OffencesListRow.tsx
packages/ui/src/features/CourtCaseList/tags/LockedByTag/LockedByButton.tsx
packages/ui/src/pages/court-cases/[courtCaseId]/index.tsx
packages/ui/src/types/CaseDetailsTab.ts
packages/ui/src/utils/updateTabLink.ts

* Replaced `herf="/"` (apart Header links)
* Add `tab` query param
* Add `tab` link backup for slow connections
* Remove spinner

Remove links sending the user to route page

---

packages/ui/src/components/CustomDateInput/DateInput.styles.tsx

Fix styling of same date button on case resolved date filter

---

packages/api/src/services/db/cases/fetchCases.ts

This was raised in SonarCloud and so main has a sad cross.
https://sonarcloud.io/project/issues?severities=BLOCKER%2CCRITICAL%2CMAJOR%2CMINOR&sinceLeakPeriod=true&issueStatuses=OPEN%2CCONFIRMED&types=BUG&id=ministryofjustice_bichard7-next-core&open=AZdEy_9EkY_Do3dEo3ls

Fix fetchCases returning NaN for full count

---

packages/api/src/services/db/cases/filters/generateFilters.ts
packages/api/src/services/db/cases/filters/showCasesWithDateDifference.e2e.test.ts
packages/api/src/services/db/cases/filters/showCasesWithDateDifference.ts
packages/api/src/types/CaseIndexQuerystring.ts
packages/api/src/useCases/cases/fetchCasesAndFilter.ts

[BICAWS7-3636](https://dsdmoj.atlassian.net/browse/BICAWS7-3636)
[BICAWS7-3637](https://dsdmoj.atlassian.net/browse/BICAWS7-3637)
[BICAWS7-3636]: https://dsdmoj.atlassian.net/browse/BICAWS7-3636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BICAWS7-3637]: https://dsdmoj.atlassian.net/browse/BICAWS7-3637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BICAWS7-3636 Add the filter to use case and add logic for DB filtering

---

packages/ui/cypress/component/FormGroup.cy.tsx
packages/ui/src/components/CustomDateInput/DateInput.tsx
packages/ui/src/components/FormGroup.tsx
packages/ui/src/components/NoteTextArea.tsx
packages/ui/src/components/Radios/RadioGroup.tsx
packages/ui/src/components/ReallocationNotesForm.tsx
packages/ui/src/components/SearchFilters/CourtDateFilter.tsx
packages/ui/src/components/SearchFilters/ReasonFilterOptions/ReasonFilter.tsx
packages/ui/src/components/SearchFilters/ResolvedDateFilter.tsx
packages/ui/src/features/CourtCaseFilters/CourtCaseFilter.tsx
packages/ui/src/pages/court-cases/[courtCaseId]/resolve.tsx
packages/ui/src/pages/feedback.tsx

Adds a reusable form group component:
* Ensures we always use the right GDS class
* Adds error class functionality

Add FormGroup component

---

packages/common/types/ExceptionQuality.ts
packages/common/types/TriggerQuality.ts
packages/ui/cypress/component/Audit/ExceptionQualityDropdown.cy.tsx
packages/ui/cypress/component/Audit/QualityStatusCard.cy.tsx
packages/ui/cypress/component/Audit/TriggerQualityDropdown.cy.tsx
packages/ui/cypress/component/Select.cy.tsx
packages/ui/src/components/Select.tsx
packages/ui/src/features/CourtCaseDetails/Sidebar/Audit/ExceptionQualityDropdown.tsx
packages/ui/src/features/CourtCaseDetails/Sidebar/Audit/QualityStatusCard.styles.tsx
packages/ui/src/features/CourtCaseDetails/Sidebar/Audit/QualityStatusCard.tsx
packages/ui/src/features/CourtCaseDetails/Sidebar/Audit/TriggerQualityDropdown.tsx

This PR adds all the components needed for audit but does not add them to the case details screen. Component tests mocking the API calls currently, I will add the actual API route in a future PR.

BICAWS7-3754 - Add auditing box

---

.circleci/continue_config.yml
packages/api/src/services/db/cases/canCaseBeResubmitted.integration.test.ts
packages/api/src/services/db/cases/canCaseBeResubmitted.ts
packages/api/src/useCases/cases/resubmit/canUserResubmitCase.integration.test.ts
packages/ui/src/config.ts
packages/ui/src/pages/court-cases/[courtCaseId]/index.tsx

* Tests were breaking as we had the wrong type
* We weren't using the API in CI, hence why we didn't get an error in CI

Fix e2e tests in pipeline
